
```{r}

library(ggpmisc)
library(tidyr)
library(dplyr)
library(stringr)
library(reshape2)
library(ggsignif)
library(patchwork)
library(qs)
library(aplot)


'%ni%'=Negate('%in%')

setwd("/home/xumeng/TCR_Dynamic/code4fithub/Fig4/")

mycol <- c("#D62728", "#1F77B4",  "#FF7F0E", "#2CA02C", "#9467BD", "#8C564B", "#E377C2", "#BCBD22", "#17BECF", "#FF9896", "#AEC7E8", "#FFBB78", "#98DF8A",  "#C5B0D5",  "#C49C94",  "#F7B6D2", "#7F7F7F", "#DBDB8D", "#9EDAE5", "#45aab4","#fe7966","#81d0bb","#f9637c","#fbb45c","#038dW2","#FFDE99","#B8C8F5","#8fa2dc","#feaac2","#206491", "gold", "seagreen", "tomato", "#285d7c", "#f1d19e", "#e5807c", "#d7969a", "#eeebd8", "#d97d56", "#eecca9", "#eeeddb", "#494651", "#4b98a9", "#719eb6", "#679bc5", "#d94248", "#ebd66d", "#62985a", "#ecc832", "#e1a34e", "#ac3241", "#f5812d", "#d63833", "#ef5a30")

```


```{r}

SCC4tissue <- qread("/home/xumeng/TCR_Dynamic/randomicity/data4fig2_sec2/SCC/SCC4tissue.qs")
BCC4tissue <- qread("/home/xumeng/TCR_Dynamic/randomicity/data4fig2_sec2/BCC/BCC4tissue.qs")
HN4tissue <- qread("/home/xumeng/TCR_Dynamic/randomicity/data4fig2_sec2/HN/HN4tissue.qs")

SCC4tissue$datasets <- "SCC"
BCC4tissue$datasets <- "BCC"
HN4tissue$datasets <- "HN"

data4tissue <- bind_rows(SCC4tissue, BCC4tissue, HN4tissue)

data4tissue$patient <- paste0(data4tissue$patient, "@", data4tissue$tissue, "@", data4tissue$datasets)

head(data4tissue)

data4dis <- data4tissue[, c("cdr3_aa_bl", "count_bl", "patient", "time")] %>% unique()
# data4dis$sampleid <- paste0(data4dis$patient, "@", data4dis$time)

head(data4dis)

data4dis <- data4dis %>%
  mutate(
    time = case_when(
      time %in% c("post") ~ "T2",
      time %in% c("pre") ~ "T1",
      time %in% c("B1") ~ "T1",
      time %in% c("B2") ~ "T2",
      TRUE ~ time
    ))

qsave(data4dis, "multi_tissue_bulk_data.qs")

```


```{r}

data4dis <- qread("multi_tissue_bulk_data.qs")

head(data4dis)

summary_stats <- unique(data4dis) %>%
  group_by(patient, time) %>%
  summarise(
    n_rows = n(),                        
    sum_count = sum(count_bl, na.rm = TRUE)  
  # ) %>%
  # summarise(
  #   mean_n_rows = mean(n_rows),          
  #   mean_sum_count = mean(sum_count)     
  )

summary_stats

write.csv(summary_stats, "multi_tissues_bulk_all_count.csv")


```



```{r}

data4dis <- qread("multi_tissue_bulk_data.qs")

data4dis_wide <- data4dis %>%
  pivot_wider(
    names_from = time,      
    values_from = count_bl,  
    values_fill = list(count_bl = 0)  
  )


head(data4dis_wide)


data4dis_wide <- data4dis_wide %>%
  mutate(
    status = case_when(
      T1 > 0 & T2 == 0 ~ "T1_only",
      T1 == 0 & T2 > 0 ~ "T2_only",
      T1 > 0 & T2 > 0 ~ "T1_T2",
    )
  )

table(data4dis_wide$status)


```


```{r}

head(data4dis)

all_TCR_count <- table(data4dis$patient, data4dis$time) %>% as.data.frame.matrix()

all_TCR_count$patient <- rownames(all_TCR_count)

head(all_TCR_count)

all_TCR_count <- all_TCR_count %>%
  rowwise() %>%
  mutate(
    T1_TCR_pct = T1 / (T1 + T2),
    T2_TCR_pct = T2 / (T1 + T2)
  ) %>%
  ungroup()

# colnames(all_TCR_count) <- c("patient", "time", "TCR_type_count")

head(all_TCR_count)


all_Tcell_count_sum <- data4dis %>%
  group_by(patient, time) %>%                           
  summarise(
     count_sum = sum(count_bl, na.rm = TRUE),
    
    ) %>%        
      
  ungroup() %>% as.data.frame()

head(all_Tcell_count_sum)


all_Tcell_count_sum <- all_Tcell_count_sum %>%
  pivot_wider(
    names_from = time,      
    values_from = count_sum,  
    values_fill = list(count_sum = 0)  
  )


all_Tcell_count_sum <- all_Tcell_count_sum %>%
  rowwise() %>%
  mutate(
    T1_TCell_pct = T1 / (T1 + T2),
    T2_TCell_pct = T2 / (T1 + T2)
  ) %>%
  ungroup()


head(all_TCR_count)
head(all_Tcell_count_sum)


all_TCR_count_1 <- all_TCR_count

colnames(all_TCR_count_1)[1:2] <- c("T1_TCR", "T2_TCR")

head(all_TCR_count_1)

# all_TCR_count_1$T1 <- NULL
# all_TCR_count_1$T2 <- NULL


all_Tcell_count_sum_1 <- all_Tcell_count_sum

colnames(all_Tcell_count_sum_1)[2:3] <- c("T1_TCell", "T2_TCell")

head(all_Tcell_count_sum_1)

# all_Tcell_count_sum_1$T1 <- NULL
# all_Tcell_count_sum_1$T2 <- NULL

all_count <- left_join(all_TCR_count_1, all_Tcell_count_sum_1, by = c("patient"))

head(all_count)

unique(all_count$patient)


```




```{r}

status_ratio <- table(data4dis_wide$patient, data4dis_wide$status) %>% as.data.frame.matrix()

status_ratio$patient <- rownames(status_ratio)

head(status_ratio)

unique(status_ratio$patient)

status_ratio <- status_ratio %>%
  rowwise() %>%
  mutate(
    po_TCR_ratio = T1_only / (T1_only + T1_T2),
  ) %>%
  mutate(
    pepr_TCR_ratio = T1_T2 / (T1_only + T1_T2),
  ) %>%
  mutate(
    pepo_TCR_ratio = T1_T2 / (T1_T2 + T2_only),
  ) %>%
  mutate(
    eg_TCR_ratio = T2_only / (T1_T2 + T2_only),
  ) %>%
  ungroup()

status_ratio <- status_ratio %>%
  rowwise() %>%
  mutate(
    depth = (T1_only + T1_T2*2 + T2_only)/ 2
  ) %>%
  ungroup()

head(status_ratio)

```




```{r}

patient_ratio <- left_join(status_ratio[, c("patient", "po_TCR_ratio", "pepr_TCR_ratio", "pepo_TCR_ratio", "eg_TCR_ratio", "depth")], all_count, by = "patient")


patient_ratio[is.na(patient_ratio)]=0


head(patient_ratio)


patient_ratio$T2_T1_TCell <- patient_ratio$T2_TCell_pct / patient_ratio$T1_TCell_pct

patient_ratio$T1_T2_TCell <- patient_ratio$T1_TCell_pct / patient_ratio$T2_TCell_pct

patient_ratio$T2_T1_TCR <- patient_ratio$T2_TCR_pct / patient_ratio$T1_TCR_pct
patient_ratio$T1_T2_TCR <- patient_ratio$T1_TCR_pct / patient_ratio$T2_TCR_pct


patient_ratio <- patient_ratio %>%
  mutate(Tissue = str_split(patient, "@", simplify = TRUE)[, 2])

patient_ratio <- patient_ratio %>%
  mutate(Datasets = str_split(patient, "@", simplify = TRUE)[, 3])

head(patient_ratio)

qsave(patient_ratio, "patient_ratio_multi_tissues_bulk.qs")

```



```{r}

patient_ratio <- qread("/home/xumeng/TCR_Dynamic/Fig/Fig2_test/multi_tissue/bulk/patient_ratio_multi_tissues_bulk.qs")

head(patient_ratio)


```

```{r}

data4po <- patient_ratio[, c("patient","po_TCR_ratio", "T1_TCell", "T1_TCR","T1_TCell_pct",  "T1_TCR_pct", "T1_T2_TCell", "T1_T2_TCR", "depth", "Tissue", "Datasets")] %>% unique()


cov <- c("T1_TCR_pct")
fmla <- as.formula(paste("po_TCR_ratio ~", paste(cov, collapse = " + ")))

fmla

model2 <- lm(fmla, data = data4po)

fitted_vals <- fitted(model2)

po4box <- data4po %>%
    mutate(adjusted_value = fitted_vals)

```



```{r}

data4eg <- patient_ratio[, c("patient","eg_TCR_ratio",  "T2_TCell", "T2_TCell_pct", "T2_TCR", "T2_TCR_pct", "T2_T1_TCell", "T2_T1_TCR", "Tissue", "Datasets" , "depth")] %>% unique()


cov <- c("T2_TCR_pct")
fmla <- as.formula(paste("eg_TCR_ratio ~", paste(cov, collapse = " + ")))

fmla

model2 <- lm(fmla, data = data4eg)

fitted_vals <- fitted(model2)

eg4box <- data4eg %>%
    mutate(adjusted_value = fitted_vals)


```


```{r}

head(po4box)

po4box_1 <- po4box[, c("patient", "adjusted_value")]
eg4box_1 <- eg4box[, c("patient", "adjusted_value")]

ts4box_1 <- left_join(po4box_1, eg4box_1, by = "patient")

colnames(ts4box_1)[2:3] <- c("po_adj", "eg_adj")

head(ts4box_1)

ts4box_long <- ts4box_1 %>%
  gather(key = "status", value = "Ratio", po_adj, eg_adj)

ts4box_long <- ts4box_long %>%
  mutate(Tissue = str_split(patient, "@", simplify = TRUE)[, 2])

head(ts4box_long)

ts4box_long$status <- factor(ts4box_long$status, levels = c("po_adj", "eg_adj"))

p2 <- ggplot(ts4box_long, aes(x = Tissue, y = as.numeric(Ratio), color = Tissue)) +
      geom_point(aes(color = Tissue), position = position_jitterdodge(0.6), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  # scale_color_npg() +   
      scale_color_manual(values = c("PBMC" = "#a01b2b", "Tumor" = "#e48d24", "BCC" = "#B17F9F", "SCC" = "#FFC89D", "HN" = "tomato")) +
      scale_y_continuous(breaks = seq(0.5, 1, 0.1), limits = c(0.5, 1.1)) +
      ggtitle("") +
      labs(
        x = NULL, y = "TCR Ratio",
        fill = "Tissue"
      ) +
      theme_classic() +
      facet_wrap(~ status, scales = "free", ncol = 2) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("Tumor", "PBMC")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )


p2


p2 <- ggplot(ts4box_long, aes(x = status, y = as.numeric(Ratio), color = status)) +
      geom_point(aes(color = status), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  # scale_color_npg() +   
      scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      # scale_y_continuous(breaks = seq(0, 1.2, 0.2)) +
      ggtitle("") +
      labs(
        x = NULL, y = "TCR Ratio",
        fill = "Tissue"
      ) +
      theme_classic() +
      facet_wrap(~ Tissue, scales = "free", ncol = 2) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("po_adj", "eg_adj")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )

p2

```


```{r}


p2 <- ggplot(patient_ratio, aes(x = Tissue, y = as.numeric(T2_TCR_pct), color = Tissue)) +
      geom_point(aes(color = Tissue), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  # scale_color_npg() +   
      scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      # scale_y_continuous(breaks = seq(0, 1.2, 0.2)) +
      ggtitle("") +
      labs(
        x = NULL, y = "T2 TCR Ratio",
        fill = "Tissue"
      ) +
      theme_classic() +
      # facet_wrap(~ Tissue, scales = "free", ncol = 2) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("Tumor", "PBMC")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )

p1 + p2





p1 <- ggplot(patient_ratio, aes(x = Tissue, y = as.numeric(T1_TCR), color = Tissue)) +
      geom_point(aes(color = Tissue), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  # scale_color_npg() +   
      scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      # scale_y_continuous(breaks = seq(0, 1.2, 0.2)) +
      ggtitle("") +
      labs(
        x = NULL, y = "T1 TCR",
        fill = "Tissue"
      ) +
      theme_classic() +
      # facet_wrap(~ Tissue, scales = "free", ncol = 2) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("Tumor", "PBMC")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )

p1

p2 <- ggplot(patient_ratio, aes(x = Tissue, y = as.numeric(T2_TCR), color = Tissue)) +
      geom_point(aes(color = Tissue), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  # scale_color_npg() +   
      scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      # scale_y_continuous(breaks = seq(0, 1.2, 0.2)) +
      ggtitle("") +
      labs(
        x = NULL, y = "T2 TCR",
        fill = "Tissue"
      ) +
      theme_classic() +
      # facet_wrap(~ Tissue, scales = "free", ncol = 2) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("Tumor", "PBMC")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )

p1 + p2

head(patient_ratio)

ts4box_long <- patient_ratio[, c("patient", "T1_TCR_pct", "T2_TCR_pct", "T1_TCR", "T2_TCR", "eg_TCR_ratio", "po_TCR_ratio")] %>%
  gather(key = "status", value = "Ratio", T1_TCR_pct, T2_TCR_pct, T1_TCR, T2_TCR, eg_TCR_ratio, po_TCR_ratio)



ts4box_long <- ts4box_long %>%
  mutate(Tissue = str_split(patient, "@", simplify = TRUE)[, 2])

head(ts4box_long)

p2 <- ggplot(subset(ts4box_long, status %in% c("T1_TCR_pct", "T2_TCR_pct")), aes(x = Tissue, y = as.numeric(Ratio), color = Tissue)) +
      geom_point(aes(color = Tissue), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  # scale_color_npg() +   
      scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      # scale_y_continuous(breaks = seq(0, 1.2, 0.2)) +
      ggtitle("") +
      labs(
        x = NULL, y = "",
        fill = "Tissue"
      ) +
      theme_classic() +
      facet_wrap(~ status, scales = "free", ncol = 2) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("Tumor", "PBMC")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )

p2


p2 <- ggplot(subset(ts4box_long, status %in% c("T1_TCR_pct", "T2_TCR_pct")), aes(x = status, y = as.numeric(Ratio), color = status)) +
      geom_point(aes(color = status), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  # scale_color_npg() +   
      scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      # scale_y_continuous(breaks = seq(0, 1.2, 0.2)) +
      ggtitle("") +
      labs(
        x = NULL, y = "",
        fill = "Tissue"
      ) +
      theme_classic() +
      facet_wrap(~ Tissue, scales = "free", ncol = 2) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("T1_TCR_pct", "T2_TCR_pct")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )


p2




p2 <- ggplot(subset(ts4box_long, status %in% c("T1_TCR", "T2_TCR")), aes(x = status, y = as.numeric(Ratio), color = status)) +
      geom_point(aes(color = status), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  # scale_color_npg() +   
      scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      # scale_y_continuous(breaks = seq(0, 1.2, 0.2)) +
      ggtitle("") +
      labs(
        x = NULL, y = "",
        fill = "Tissue"
      ) +
      theme_classic() +
      facet_wrap(~ Tissue, scales = "free", ncol = 2) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("T1_TCR", "T2_TCR")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )


p2



p2 <- ggplot(subset(ts4box_long, status %in% c("po_TCR_ratio", "eg_TCR_ratio")), aes(x = Tissue, y = as.numeric(Ratio), color = Tissue)) +
      geom_point(aes(color = Tissue), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  # scale_color_npg() +   
      scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      # scale_y_continuous(breaks = seq(0, 1.2, 0.2)) +
      ggtitle("") +
      labs(
        x = NULL, y = "",
        fill = "Tissue"
      ) +
      theme_classic() +
      facet_wrap(~ status, scales = "free", ncol = 2) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("Tumor", "PBMC")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )

p2



p2 <- ggplot(subset(ts4box_long, status %in% c("po_TCR_ratio", "eg_TCR_ratio")), aes(x = status, y = as.numeric(Ratio), color = status)) +
      geom_point(aes(color = status), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  # scale_color_npg() +   
      scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      # scale_y_continuous(breaks = seq(0, 1.2, 0.2)) +
      ggtitle("") +
      labs(
        x = NULL, y = "",
        fill = "Tissue"
      ) +
      theme_classic() +
      facet_wrap(~ Tissue, scales = "free", ncol = 2) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("po_TCR_ratio", "eg_TCR_ratio")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )

p2



```

