```{r}
setwd("/home/xumeng/TCR_Dynamic/code4fithub/Fig4/")

library(ggpmisc)
library(tidyr)
library(dplyr)
library(stringr)
library(reshape2)
library(ggsignif)
library(patchwork)
library(qs)
library(aplot)


mycol <- c("#1F77B4",  "#FF7F0E", "#2CA02C", "#9467BD", "#8C564B", "#E377C2", "#BCBD22", "#17BECF", "#FF9896", "#AEC7E8", "#FFBB78", "#D62728", "#98DF8A",  "#C5B0D5",  "#C49C94",  "#F7B6D2", "#7F7F7F", "#DBDB8D", "#9EDAE5", "#45aab4","#fe7966","#81d0bb","#f9637c","#fbb45c","#038dW2","#FFDE99","#B8C8F5","#8fa2dc","#feaac2","#206491", "gold", "seagreen", "tomato", "#285d7c", "#f1d19e", "#e5807c", "#d7969a", "#eeebd8", "#d97d56", "#eecca9", "#eeeddb", "#494651", "#4b98a9", "#719eb6", "#679bc5", "#d94248", "#ebd66d", "#62985a", "#ecc832", "#e1a34e", "#ac3241", "#f5812d", "#d63833", "#ef5a30")

```


```{r}

generate_tcr_simple <- function(n, quantile_probs, quantile_values, prefix = "TCR") {

  quantile_function <- approxfun(quantile_probs, quantile_values, method = "linear", rule = 2)

  counts <- round(quantile_function(runif(n)))
  
  tcr_ids <- paste0(prefix, seq_len(n))
  
  data <- data.frame(TCR = tcr_ids, Count = counts)
  
  return(data)
}

```






```{r}

quantile_probs <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.975, 0.99, 0.995, 0.999, 1)

# 90%
quantile_values0 <- c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 16, 128, 512, 10000)


set.seed(42)  

tcr_data0 <- generate_tcr_simple(n = 1000000, quantile_probs = quantile_probs, quantile_values = quantile_values0)

# 80%
quantile_values1 <- c(1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 5, 32, 128, 512, 10000)


set.seed(42)  

tcr_data1 <- generate_tcr_simple(n = 1000000, quantile_probs = quantile_probs, quantile_values = quantile_values1)



# 70%
quantile_values2 <- c(1, 1, 1, 1, 1, 1, 1, 1, 2, 4, 8, 16, 64, 128, 512, 10000)


set.seed(42)  

tcr_data2 <- generate_tcr_simple(n = 1000000, quantile_probs = quantile_probs, quantile_values = quantile_values2)


# 60%
quantile_values3 <- c(1, 1, 1, 1, 1, 1, 1, 2, 4, 6, 8, 32, 64, 128, 512, 10000)


set.seed(42)  

tcr_data3 <- generate_tcr_simple(n = 1000000, quantile_probs = quantile_probs, quantile_values = quantile_values3)


# 50%
quantile_values4 <- c(1, 1, 1, 1, 1, 1, 2, 2, 4, 6, 12, 24, 64, 128, 512, 10000)


set.seed(42)  

tcr_data4 <- generate_tcr_simple(n = 1000000, quantile_probs = quantile_probs, quantile_values = quantile_values4)


# 40%
quantile_values5 <- c(1, 1, 1, 1, 1, 2, 2, 4, 6, 8, 16, 32, 128, 256, 512, 10000)


set.seed(42)  

tcr_data5 <- generate_tcr_simple(n = 1000000, quantile_probs = quantile_probs, quantile_values = quantile_values5)



# 30%
quantile_values6 <- c(1, 1, 1, 1, 2, 2, 4, 6, 8, 16, 32, 64, 128, 256, 512,  10000)


set.seed(42)  

tcr_data6 <- generate_tcr_simple(n = 1000000, quantile_probs = quantile_probs, quantile_values = quantile_values6)



# 20%
quantile_values7 <- c(1, 1, 1, 2, 2, 3, 4, 8, 12, 16, 32, 64, 128, 256, 512, 10000)


set.seed(42)  

tcr_data7 <- generate_tcr_simple(n = 1000000, quantile_probs = quantile_probs, quantile_values = quantile_values7)



# 10%
quantile_values8 <- c(1, 1, 2, 2, 3, 4, 6, 8, 16, 24, 32, 64, 128, 256, 512, 10000)


set.seed(42)  

tcr_data8 <- generate_tcr_simple(n = 1000000, quantile_probs = quantile_probs, quantile_values = quantile_values8)


# 0%
quantile_values9 <- c(1, 2, 2, 3, 4, 6, 8, 12, 16, 24, 32, 64, 128, 256, 512, 10000)


set.seed(42)  

tcr_data9 <- generate_tcr_simple(n = 1000000, quantile_probs = quantile_probs, quantile_values = quantile_values9)


# 0%
quantile_values10 <- c(2, 2, 2, 3, 4, 6, 8, 12, 16, 24, 48, 64, 128, 256, 512, 10000)


set.seed(42)  

tcr_data10 <- generate_tcr_simple(n = 1000000, quantile_probs = quantile_probs, quantile_values = quantile_values10)


```



```{r}

all_bulk <- qread("/home/xumeng/TCR_Dynamic/Fig/Fig2_p2/all_bulk.qs")

all_bulk <- qread("/home/xumeng/TCR_Dynamic/Fig/Fig2_simu1/all_bulk_0407.qs")


# getwd()
all_bulk$count <- all_bulk$count_bl

all_bulk$sampleid <- paste0(all_bulk$patient, "@", all_bulk$time)

head(all_bulk)


quantiles <- subset(all_bulk, count > 0) %>%
# group_by(sampleid, Datasets) %>%
group_by(sampleid) %>%
  summarize(
    min = min(count),
    q10 = quantile(count, 0.1),
    q20 = quantile(count, 0.2),
    q30 = quantile(count, 0.3),
    q40 = quantile(count, 0.4),
    q50 = quantile(count, 0.5),
    q60 = quantile(count, 0.6),
    q70 = quantile(count, 0.7),
    q80 = quantile(count, 0.8),
    q90 = quantile(count, 0.9),
    q95 = quantile(count, 0.95),
    q975 = quantile(count, 0.975),
    q99 = quantile(count, 0.99),
    q995 = quantile(count, 0.995),
    q999 = quantile(count, 0.999),
    max = max(count),
  )


quantiles_table <- quantiles %>%
  mutate(across(where(is.numeric), round, digits = 2)) %>% 
  as.data.frame()

quantiles_table_1 <- quantiles_table %>%
  filter(!grepl("HCD", sampleid))

quantiles_table_1 <- quantiles_table_1 %>%
  filter(!grepl("HPV", sampleid))

# quantiles_table_1 <- quantiles_table

average_df <- quantiles_table_1 %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE)) %>% t() %>% as.data.frame()

# average_df


quantile_df <- data.frame(
  quantile0 = quantile_values0,
  quantile1 = quantile_values1,
  quantile2 = quantile_values2,
  quantile3 = quantile_values3,
  quantile4 = quantile_values4,
  quantile5 = quantile_values5,
  quantile6 = quantile_values6,
  quantile7 = quantile_values7,
  quantile8 = quantile_values8,
  quantile9 = quantile_values9,
  quantile10 = quantile_values10,
  quantile_mean = round(average_df$V1, 1)
)


head(quantile_df)

rownames(quantile_df) <- c("min", "q10", "q20", "q30", "q40", "q50", "q60", "q70", "q80", "q90", "q95", "q975", "q99", "q995", "q999", "max")

library(tidyverse)

quantile_df <- quantile_df %>%
  rownames_to_column(var = "qlevel")



quantile_df_long <- quantile_df %>%

  pivot_longer(
    cols = starts_with("quantile"), 
    names_to = "group",             
    values_to = "value"              
  )


head(quantile_df_long)


quantile_df_long$qlevel <- factor(quantile_df_long$qlevel, levels = c("min", "q10", "q20", "q30", "q40", "q50", "q60", "q70", "q80", "q90", "q95", "q975", "q99", "q995", "q999", "max"))

quantile_df_long$group <- factor(quantile_df_long$group, levels = colnames(quantile_df)[2:13])

head(quantile_df_long)


'%ni%'=Negate('%in%')


p <- ggplot(subset(quantile_df_long, qlevel %ni% c("q995", "q999")), aes(x = qlevel, y = log2(value), group = group, color = group)) +
  geom_point(size = 1) +
  geom_line(linewidth = 0.2) +
  # facet_wrap(~ Datasets) +
  labs(x = "Quantile", y = "Log2(Clonosize)") +
  scale_color_manual(values = mycol)+
  theme_bw()+
  theme(
    plot.title = element_text(size = 8, color = "black", hjust = 0.5),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 6, color = "black"),
    axis.text.y = element_text(size = 6, color = "black"),
    axis.title.y = element_text(size = 7, color = "black"),
    axis.title.x = element_text(size = 7, color = "black"),
    axis.line = element_blank(),
    axis.ticks = element_line(linewidth = 0.2),
    panel.grid = element_line(linewidth = 0.2),
    legend.position = "right",
    legend.text = element_text(size = 6),
    legend.title = element_text(size = 7),
  )

p



```




```{r}

simu_T_0 <- rep(tcr_data0$TCR, tcr_data0$Count) 
simu_T_1 <- rep(tcr_data1$TCR, tcr_data1$Count) 
simu_T_2 <- rep(tcr_data2$TCR, tcr_data2$Count) 
simu_T_3 <- rep(tcr_data3$TCR, tcr_data3$Count) 
simu_T_4 <- rep(tcr_data4$TCR, tcr_data4$Count) 
simu_T_5 <- rep(tcr_data5$TCR, tcr_data5$Count) 
simu_T_6 <- rep(tcr_data6$TCR, tcr_data6$Count) 
simu_T_7 <- rep(tcr_data7$TCR, tcr_data7$Count) 
simu_T_8 <- rep(tcr_data8$TCR, tcr_data8$Count) 
simu_T_9 <- rep(tcr_data9$TCR, tcr_data9$Count) 
simu_T_10 <- rep(tcr_data9$TCR, tcr_data10$Count) 

simu_T <- list(simu_T_0, simu_T_1, simu_T_2, simu_T_3, simu_T_4, simu_T_5, simu_T_6, simu_T_7, simu_T_8, simu_T_9, simu_T_10)


# simu_T <- list(simu_T_1, simu_T_2, simu_T_3)

# simu_T <- list(simu_T_1)

```


```{r}


length(simu_T)



pe_sampling <- NULL


# sn <- 10^seq(5, 8)

# sn <- seq(1*10^5, 3*10^6, 1*10^5)

sn <- c(seq(0.002, 0.008, 0.002), seq(0.01, 0.09, 0.01), seq(0.1, 0.5, 0.1))

for (si in seq(1,11,1)){

simu_T_tmp <- simu_T[[si]]


simu_T_with_id <- paste0(simu_T_tmp, "_", seq_along(simu_T_tmp))


for ( i in sn) {
  # for ( j in sn) {
    for ( k in seq(1, 3, 1)) {

# print(paste0(i, "_", j, "_", k))
print(paste0(si, "_", i, "_",  k))


Pre_1w_indices <- sample(seq_along(simu_T_tmp), i * length(simu_T_tmp), replace = FALSE)
Pre_1w <- simu_T_tmp[Pre_1w_indices]

head(Pre_1w)


remaining_indices <- setdiff(seq_along(simu_T_tmp), Pre_1w_indices)


Post_1w_indices <- sample(remaining_indices, min(i * length(simu_T_tmp), length(remaining_indices)), replace = FALSE)

Post_1w <- simu_T_tmp[Post_1w_indices]

Pre_1w_1 <- table(Pre_1w) %>% as.data.frame()
colnames(Pre_1w_1) <- c("TCR", "Pre")
# head(Pre_1w_1)
dim(Pre_1w_1)

Post_1w_1 <- table(Post_1w) %>% as.data.frame()
colnames(Post_1w_1) <- c("TCR", "Post")


new_1w <- merge(Pre_1w_1, Post_1w_1, by = "TCR", all = TRUE)


new_1w[is.na(new_1w)] <- 0

new_1w <- new_1w %>%
  mutate(
    status = case_when(
      Pre > 0 & Post == 0 ~ "only",
      Pre == 0 & Post > 0 ~ "only",
      Pre > 0 & Post > 0 ~ "across"
    )
  )


head(new_1w)
dim(new_1w)


type_ratio1 <- table(subset(new_1w, Pre> 0)$status) %>% as.data.frame()
colnames(type_ratio1) <- c("type", "count")

# type_ratio1

type_ratio1 <- type_ratio1 %>%
  mutate(ratio = count / sum(count))

type_ratio1$time <- "Pre"

type_ratio2 <- table(subset(new_1w, Post > 0)$status) %>% as.data.frame()
colnames(type_ratio2) <- c("type", "count")

# type_ratio2

type_ratio2 <- type_ratio2 %>%
  mutate(ratio = count / sum(count))

type_ratio2$time <- "Post"

type_ratio <- bind_rows(type_ratio1, type_ratio2)

type_ratio$sampling <- paste0("S", k)
type_ratio$s_ratio <- i
type_ratio$simu <- si

head(type_ratio)

pe_sampling <- bind_rows(pe_sampling, type_ratio)


    }
}
  
}
 

head(pe_sampling)


```



```{r}

qsave(pe_sampling, "pe_sampling_dengbi_with_wultiex.qs")


```


```{r}

head(pe_sampling)

pe_sampling$type <- paste0(pe_sampling$time, "@", pe_sampling$type)

pe_sampling$type <- factor(pe_sampling$type, levels = c("Pre@only", "Pre@across", "Post@only", "Post@across"  ))

head(pe_sampling)

pe_sampling$s_ratio <- factor(pe_sampling$s_ratio)

pe_sampling$simu <- factor(pe_sampling$simu)

color_ten <- c("#699ECA", "#D65190", "red","#FF8C00", "#F898CB", "#731A73", "#FFCB5B", "#4DAF4A", "#E87B1E", "#0076B9", "#3D505A", "#0098B2")


p1 <- ggplot(pe_sampling, aes(x = s_ratio, y = ratio, group = simu, color = simu)) +
  # geom_boxplot(aes(group = interaction(post_n, pre_n)), alpha = 0.5, position = position_dodge(width = 0)) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
        geom="errorbar", aes(color = simu), width=0.2, linewidth = 0.2,) +
  stat_summary(fun = mean, geom="point", size = 0.5, aes(color = simu)) +
  stat_summary(fun = mean, geom = "line", aes(group = simu), linewidth = 0.1) +
  scale_color_manual(values = color_ten) +
    scale_y_continuous(breaks = seq(0,1,0.1)) + 
facet_wrap(~ type, ncol = 4, scales = "fixed") +
  theme_bw() +
  labs(x = "N pre", y = "TCR Ratio", title = "") +
  theme(
    plot.title=element_text(size=7, color = "black"),
    axis.text.x = element_text(angle = 45, size = 7, hjust = 1, color = "black"),
    axis.text.y = element_text(size=6, color = "black"),
    # axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2), 
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "right",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  )


p1



```



```{r}


quantile_probs <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.975, 0.99, 0.995, 0.999, 1)


# 70%
quantile_values2 <- c(1, 1, 1, 1, 1, 1, 1, 1, 2, 4, 8, 16, 64, 128, 512, 10000)


set.seed(42)  

tcr_data2_1 <- generate_tcr_simple(n = 100000, quantile_probs = quantile_probs, quantile_values = quantile_values2)

tcr_data2_2 <- generate_tcr_simple(n = 1000000, quantile_probs = quantile_probs, quantile_values = quantile_values2)

tcr_data2_3 <- generate_tcr_simple(n = 10000000, quantile_probs = quantile_probs, quantile_values = quantile_values2)





simu_T_2_1 <- rep(tcr_data2_1$TCR, tcr_data2_1$Count) # 70%
simu_T_2_2 <- rep(tcr_data2_2$TCR, tcr_data2_2$Count) # 70%
simu_T_2_3 <- rep(tcr_data2_3$TCR, tcr_data2_3$Count) # 70%


simu_T <- list(simu_T_2_1, simu_T_2_2, simu_T_2_3)  #, simu_T_2_4)

```


```{r}

pe_sampling <- NULL


sn <- c(seq(0.002, 0.008, 0.002), seq(0.01, 0.09, 0.01), seq(0.1, 0.5, 0.1))


for (si in seq(1,3,1)){

simu_T_tmp <- simu_T[[si]]


simu_T_with_id <- paste0(simu_T_tmp, "_", seq_along(simu_T_tmp))


for ( i in sn) {
  # for ( j in sn) {
    for ( k in seq(1, 3, 1)) {

# print(paste0(i, "_", j, "_", k))
print(paste0(si, "_", i, "_",  k))


Pre_1w_indices <- sample(seq_along(simu_T_tmp), i * length(simu_T_tmp), replace = FALSE)
Pre_1w <- simu_T_tmp[Pre_1w_indices]

head(Pre_1w)


remaining_indices <- setdiff(seq_along(simu_T_tmp), Pre_1w_indices)


Post_1w_indices <- sample(remaining_indices, min(i * length(simu_T_tmp), length(remaining_indices)), replace = FALSE)

Post_1w <- simu_T_tmp[Post_1w_indices]

Pre_1w_1 <- table(Pre_1w) %>% as.data.frame()
colnames(Pre_1w_1) <- c("TCR", "Pre")
# head(Pre_1w_1)
dim(Pre_1w_1)

Post_1w_1 <- table(Post_1w) %>% as.data.frame()
colnames(Post_1w_1) <- c("TCR", "Post")


new_1w <- merge(Pre_1w_1, Post_1w_1, by = "TCR", all = TRUE)


new_1w[is.na(new_1w)] <- 0

new_1w <- new_1w %>%
  mutate(
    status = case_when(
      Pre > 0 & Post == 0 ~ "only",
      Pre == 0 & Post > 0 ~ "only",
      Pre > 0 & Post > 0 ~ "across"
    )
  )


head(new_1w)
dim(new_1w)


type_ratio1 <- table(subset(new_1w, Pre> 0)$status) %>% as.data.frame()
colnames(type_ratio1) <- c("type", "count")

# type_ratio1

type_ratio1 <- type_ratio1 %>%
  mutate(ratio = count / sum(count))

type_ratio1$time <- "Pre"

type_ratio2 <- table(subset(new_1w, Post > 0)$status) %>% as.data.frame()
colnames(type_ratio2) <- c("type", "count")

# type_ratio2

type_ratio2 <- type_ratio2 %>%
  mutate(ratio = count / sum(count))

type_ratio2$time <- "Post"

type_ratio <- bind_rows(type_ratio1, type_ratio2)

type_ratio$sampling <- paste0("S", k)
type_ratio$s_ratio <- i
type_ratio$simu <- si

head(type_ratio)

pe_sampling <- bind_rows(pe_sampling, type_ratio)


    }
}
  
}


qsave(pe_sampling, "pe_sampling_dengbi_with_multinumber.qs")


head(pe_sampling)


pe_sampling$type <- paste0(pe_sampling$time, "@", pe_sampling$type)

pe_sampling$type <- factor(pe_sampling$type, levels = c("Pre@only", "Pre@across", "Post@only", "Post@across"  ))

pe_sampling$s_ratio <- factor(pe_sampling$s_ratio)

pe_sampling$simu <- factor(pe_sampling$simu)


color_ten <- c("#699ECA", "#D65190", "#FF8C00", "#F898CB", "#731A73", "#FFCB5B", "#4DAF4A", "#E87B1E", "#0076B9", "#3D505A", "#0098B2")

head(pe_sampling)

p1 <- ggplot(pe_sampling, aes(x = s_ratio, y = ratio, group = simu, color = simu)) +
  # geom_boxplot(aes(group = interaction(post_n, pre_n)), alpha = 0.5, position = position_dodge(width = 0)) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
        geom="errorbar", aes(color = simu), width=0.2, linewidth = 0.2,) +
  stat_summary(fun.y=mean, geom="point", size = 0.5, aes(color = simu)) +
  stat_summary(fun = mean, geom = "line", aes(group = simu), linewidth = 0.1) +
  scale_color_manual(values = color_ten) +
    scale_y_continuous(breaks = seq(0,1,0.1)) + 
facet_wrap(~ type, ncol = 4, scales = "fixed") +
  theme_bw() +
  labs(x = "N pre", y = "TCR Ratio", title = "") +
  theme(
    plot.title=element_text(size=7, color = "black"),
    axis.text.x = element_text(angle = 45, size = 7, hjust = 1, color = "black"),
    axis.text.y = element_text(size=6, color = "black"),
    # axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2), 
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "right",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  )

p1



```



```{r}


length(simu_T)

str(simu_T)

pe_sampling <- NULL


sn <- c(seq(0.05, 0.5, 0.05))


simu_T_tmp <- simu_T[[2]]


simu_T_with_id <- paste0(simu_T_tmp, "_", seq_along(simu_T_tmp))


for ( i in sn) {
  for ( j in sn) {
    for ( k in seq(1, 3, 1)) {

print(paste0(i, "_", j, "_", k))


Pre_1w_indices <- sample(seq_along(simu_T_tmp), i * length(simu_T_tmp), replace = FALSE)
Pre_1w <- simu_T_tmp[Pre_1w_indices]

head(Pre_1w)


remaining_indices <- setdiff(seq_along(simu_T_tmp), Pre_1w_indices)


Post_1w_indices <- sample(remaining_indices, min(j * length(simu_T_tmp), length(remaining_indices)), replace = FALSE)

Post_1w <- simu_T_tmp[Post_1w_indices]

Pre_1w_1 <- table(Pre_1w) %>% as.data.frame()
colnames(Pre_1w_1) <- c("TCR", "Pre")
# head(Pre_1w_1)
dim(Pre_1w_1)

Post_1w_1 <- table(Post_1w) %>% as.data.frame()
colnames(Post_1w_1) <- c("TCR", "Post")


new_1w <- merge(Pre_1w_1, Post_1w_1, by = "TCR", all = TRUE)


new_1w[is.na(new_1w)] <- 0

new_1w <- new_1w %>%
  mutate(
    status = case_when(
      Pre > 0 & Post == 0 ~ "only",
      Pre == 0 & Post > 0 ~ "only",
      Pre > 0 & Post > 0 ~ "across"
    )
  )


head(new_1w)
dim(new_1w)


type_ratio1 <- table(subset(new_1w, Pre> 0)$status) %>% as.data.frame()
colnames(type_ratio1) <- c("type", "count")

# type_ratio1

type_ratio1 <- type_ratio1 %>%
  mutate(ratio = count / sum(count))

type_ratio1$time <- "Pre"

type_ratio2 <- table(subset(new_1w, Post > 0)$status) %>% as.data.frame()
colnames(type_ratio2) <- c("type", "count")

# type_ratio2

type_ratio2 <- type_ratio2 %>%
  mutate(ratio = count / sum(count))

type_ratio2$time <- "Post"

type_ratio <- bind_rows(type_ratio1, type_ratio2)

type_ratio$sampling <- paste0("S", k)
type_ratio$s_ratio_1 <- i
type_ratio$s_ratio_2 <- j
type_ratio$simu <- 1000000

head(type_ratio)

pe_sampling <- bind_rows(pe_sampling, type_ratio)

    }
    }
}


head(pe_sampling)

qsave(pe_sampling, "pe_sampling_budengbi.qs")

```



```{r}

head(pe_sampling)

pe_sampling$type <- paste0(pe_sampling$time, "@", pe_sampling$type)

pe_sampling$type <- factor(pe_sampling$type, levels = c("Pre@only", "Pre@across", "Post@only", "Post@across"  ))


head(pe_sampling)

pe_sampling$s_ratio_1 <- factor(pe_sampling$s_ratio_1)
pe_sampling$s_ratio_2 <- factor(pe_sampling$s_ratio_2)

pe_sampling$simu <- factor(pe_sampling$simu)

head(pe_sampling)


mycol1 <- c("#D62728", "#1F77B4",  "#FF7F0E", "#2CA02C", "#9467BD", "#8C564B", "#E377C2", "#BCBD22", "#17BECF", "#FF9896", "#AEC7E8", "#FFBB78", "#98DF8A",  "#C5B0D5",  "#C49C94",  "#F7B6D2", "#7F7F7F", "#DBDB8D", "#9EDAE5", "#45aab4","#fe7966","#81d0bb","#f9637c","#fbb45c","#038dW2","#FFDE99","#B8C8F5","#8fa2dc","#feaac2","#206491", "gold", "seagreen", "tomato", "#285d7c", "#f1d19e", "#e5807c", "#d7969a", "#eeebd8", "#d97d56", "#eecca9", "#eeeddb", "#494651", "#4b98a9", "#719eb6", "#679bc5", "#d94248", "#ebd66d", "#62985a", "#ecc832", "#e1a34e", "#ac3241", "#f5812d", "#d63833", "#ef5a30")

p1 <- ggplot(pe_sampling, aes(x = s_ratio_2, y = ratio, group = s_ratio_1, color = s_ratio_1)) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
        geom="errorbar", aes(color = s_ratio_1), width=0.2, linewidth = 0.2,) +
  stat_summary(fun.y=mean, geom="point", size = 0.6, aes(color = s_ratio_1)) +
  stat_summary(fun = mean, geom = "line", aes(group = s_ratio_1), linewidth = 0.1) +
  scale_color_manual(values = mycol1) +
    scale_y_continuous(breaks = seq(0,1,0.1)) + 
facet_wrap(~ type, ncol = 4, scales = "fixed") +
  theme_bw() +
  labs(x = "N pre", y = "TCR Ratio", title = "") +
  theme(
    plot.title=element_text(size=7, color = "black"),
    axis.text.x = element_text(angle = 45, size = 7, hjust = 1, color = "black"),
    axis.text.y = element_text(size=6, color = "black"),
    # axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2), 
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "right",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  )

p1


p1 <- ggplot(subset(pe_sampling, type %in% c("Pre@only", "Post@only")), aes(x = s_ratio_2, y = ratio, group = s_ratio_1, color = s_ratio_1)) +
  # geom_boxplot(aes(group = interaction(post_n, pre_n)), alpha = 0.5, position = position_dodge(width = 0)) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
        geom="errorbar", aes(color = s_ratio_1), width=0.2, linewidth = 0.2,) +
  stat_summary(fun.y=mean, geom="point", size = 0.6, aes(color = s_ratio_1)) +
  stat_summary(fun = mean, geom = "line", aes(group = s_ratio_1), linewidth = 0.1) +
  scale_color_manual(values = mycol) +
    scale_y_continuous(breaks = seq(0,1,0.1)) + 
facet_wrap(~ type, ncol = 4, scales = "fixed") +
  theme_bw() +
  labs(x = "N pre", y = "TCR Ratio", title = "") +
  theme(
    plot.title=element_text(size=7, color = "black"),
    axis.text.x = element_text(angle = 45, size = 7, hjust = 1, color = "black"),
    axis.text.y = element_text(size=6, color = "black"),
    # axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2), 
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "right",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  )

p1

p1 <- ggplot(subset(pe_sampling, type %in% c("Pre@across", "Post@across")), aes(x = s_ratio_2, y = ratio, group = s_ratio_1, color = s_ratio_1)) +
  # geom_boxplot(aes(group = interaction(post_n, pre_n)), alpha = 0.5, position = position_dodge(width = 0)) +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
        geom="errorbar", aes(color = s_ratio_1), width=0.2, linewidth = 0.2,) +
  stat_summary(fun.y=mean, geom="point", size = 0.6, aes(color = s_ratio_1)) +
  stat_summary(fun = mean, geom = "line", aes(group = s_ratio_1), linewidth = 0.1) +
  scale_color_manual(values = mycol) +
    scale_y_continuous(breaks = seq(0,1,0.1)) + 
facet_wrap(~ type, ncol = 4, scales = "fixed") +
  theme_bw() +
  labs(x = "N pre", y = "TCR Ratio", title = "") +
  theme(
    plot.title=element_text(size=7, color = "black"),
    axis.text.x = element_text(angle = 45, size = 7, hjust = 1, color = "black"),
    axis.text.y = element_text(size=6, color = "black"),
    # axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2), 
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "right",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  )

p1

```



