

```{r}

rm(list = ls())

library(tidyr)
library(dplyr)
library(stringr)
library(reshape2)
library(ggsignif)
library(patchwork)
library(qs)


'%ni%'=Negate('%in%')

setwd("~/TCR_Dynamic/Fig/Fig2_p2/")

mycol <- c("#D62728", "#1F77B4",  "#FF7F0E", "#2CA02C", "#9467BD", "#8C564B", "#E377C2", "#BCBD22", "#17BECF", "#FF9896", "#AEC7E8", "#FFBB78", "#98DF8A",  "#C5B0D5",  "#C49C94",  "#F7B6D2", "#7F7F7F", "#DBDB8D", "#9EDAE5", "#45aab4","#fe7966","#81d0bb","#f9637c","#fbb45c","#038db2","#FFDE99","#B8C8F5","#8fa2dc","#feaac2","#206491", "gold", "seagreen", "tomato", "#285d7c", "#f1d19e", "#e5807c", "#d7969a", "#eeebd8", "#d97d56", "#eecca9", "#eeeddb", "#494651", "#4b98a9", "#719eb6", "#679bc5", "#d94248", "#ebd66d", "#62985a", "#ecc832", "#e1a34e", "#ac3241", "#f5812d", "#d63833", "#ef5a30")

```


```{r}


pat_status <- qread("~/TCR_Dynamic/Fig/Fig2_p2/pat_status_all.qs")

head(pat_status)

comp <- list(c("only", "across"))

pat_status$status <- factor(pat_status$status, levels = c("only", "across"))

table(pat_status$datasets)
table(pat_status$type)

pat_status$facet_group <- interaction(pat_status$type, pat_status$time, pat_status$status)  # 把 type+time 合成一个分组



type_colors <- c(
  "Health" = "#66C2A5",
  "Infection" = "#FC8D62",
  "ICB" = "#8DA0CB",
  "SBRT" = "#E78AC3",
  "Trans" = "#A6D854",
  "TLGL" = "#FFD92F"
)


summary_dat <- pat_status %>%  
group_by(type, time, status) %>%  
summarise(    Mean = mean(proportion),    
SE = sd(proportion)/sqrt(n())  )


p1 <- ggplot(data = summary_dat, aes(x=status, y=type, fill = Mean)) +
geom_tile(linewidth = 0.15, alpha = 0.9) +
geom_text(aes(label = sprintf("%.2f", Mean)), color = "black", size = 2) +
scale_fill_gradientn(
        colors = rev(c("#e59f24", "white","#57acaa"))) +
facet_grid(~ time, scales = "fixed") +
ggtitle("") +
theme_minimal() +
theme(
    text = element_text(size = 6,  color = "black"),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    axis.title.x = element_text(size = 9,  color = "black"),
    axis.title.y = element_text(size = 9,  color = "black"),
    axis.text.x = element_text(size = 8,  color = "black"),
    axis.text.y = element_text(size = 9,  color = "black"),
    #legend.title = element_text(angle = 90, hjust = 0.5),
    panel.border = element_rect(color = "black", fill = NA, linewidth = .2),
    # panel.border = element_rect(color = "black", fill = NA, linewidth = 0.2),
    strip.text.x = element_text(size = 9, colour = "black"),
    strip.background = element_rect(color = "white", fill = "white"),
    axis.ticks.x=element_blank(),
    axis.ticks.y=element_blank(),
    axis.line = element_line(linewidth = 0.1),  
    axis.ticks = element_line(linewidth = 0.1), 
    legend.position = "right",
    panel.grid=element_blank())+
        coord_fixed() 

p1

summary_dat <- pat_status %>%  
group_by(time, status) %>%  
summarise(    Mean = mean(proportion),    
SE = sd(proportion)/sqrt(n())  )


p2 <- ggplot() +  
geom_bar(data = pat_status, aes(x = status, y = as.numeric(proportion), color = status), stat = "summary", fun = "mean", fill = "white", linewidth = 0.2, width = 0.8 ) +  
geom_point(data = pat_status, aes(x = status, y = as.numeric(proportion), color = status), position = position_jitterdodge(0.95), alpha = 0.6, size = 1, stroke = NA, shape = 19)+ 
geom_errorbar(data = summary_dat, aes(x = status, ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.1, color = "black") +
scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1)) +  
scale_color_manual(values = c("#e59f24", "#57acaa")) +  
facet_wrap(~ time, ncol = 12, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "TCR Ratio",
    color = "time status"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  ~
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "none",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) +
  geom_signif(data = pat_status, aes(x = status, y = as.numeric(proportion)),
    comparisons = list(c("only", "across")), step_increase = 0.08,
    map_signif_level = T, test = "wilcox.test", test.args=list(alternative = "two.side", paired = T),
    tip_length = c(0), color = "black", size = 0.2, textsize = 3
  )

p2


library(aplot)

p <- p1 %>%
  insert_top(p2, height=.3) 

p


```



```{r}

ex_data <- qread("~/TCR_Dynamic/Fig/Fig2_p2/ex_data_all_1.5.qs")

head(ex_data)

comp <- list(c("only", "across"))

table(ex_data$datasets)
table(ex_data$status)
table(ex_data$time)
table(ex_data$status, ex_data$datasets)

ex_data <- subset(ex_data, expansion == "ex")

ex_data$status <- factor(ex_data$status, levels = c("only", "across"))



summary_dat <- ex_data %>%   
group_by(type, time, status) %>%  
summarise(    Mean = mean(proportion),    
SE = sd(proportion)/sqrt(n())  )


p1 <- ggplot(data = summary_dat, aes(x=status, y=type, fill = Mean)) +
geom_tile(linewidth = 0.15, alpha = 0.9) +
geom_text(aes(label = sprintf("%.2f", Mean)), color = "black", size = 2) +
scale_fill_gradientn(
        colors = rev(c("#e59f24", "white","#57acaa"))) +
facet_grid( ~ time, scales = "fixed") +
ggtitle("") +
theme_minimal() +
theme(
    text = element_text(size = 6,  color = "black"),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    axis.title.x = element_text(size = 9,  color = "black"),
    axis.title.y = element_text(size = 9,  color = "black"),
    axis.text.x = element_text(size = 8,  color = "black"),
    axis.text.y = element_text(size = 9,  color = "black"),
    #legend.title = element_text(angle = 90, hjust = 0.5),
    panel.border = element_rect(color = "black", fill = NA, linewidth = .2),
    # panel.border = element_rect(color = "black", fill = NA, linewidth = 0.2),
    strip.text.x = element_text(size = 9, colour = "black"),
    strip.background = element_rect(color = "white", fill = "white"),
    axis.ticks.x=element_blank(),
    axis.ticks.y=element_blank(),
    axis.line = element_line(linewidth = 0.1),  ~
    axis.ticks = element_line(linewidth = 0.1), 
    legend.position = "none",
    panel.grid=element_blank())+
        coord_fixed() 
p1


summary_dat <- ex_data %>%  
group_by(time, status) %>%  
summarise(    Mean = mean(proportion),    
SE = sd(proportion)/sqrt(n())  )


p2 <- ggplot() +  
geom_bar(data = ex_data, aes(x = status, y = as.numeric(proportion), color = status), stat = "summary", fun = "mean", fill = "white", linewidth = 0.2, width = 0.8 ) +  
geom_point(data = ex_data, aes(x = status, y = as.numeric(proportion), color = status), position = position_jitterdodge(0.95), alpha = 0.6, size = 1, stroke = NA, shape = 19)+ 
geom_errorbar(data = summary_dat, aes(x = status, ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.1, color = "black") +
scale_y_continuous(expand = c(0, 0), limits = c(0, 0.9)) +  
scale_color_manual(values = c("#e59f24", "#57acaa")) +  
facet_wrap(~ time, ncol = 12, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "TCR Ratio",
    color = "time status"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  ~
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "none",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) +
  geom_signif(data = ex_data, aes(x = status, y = as.numeric(proportion)),
    comparisons = list(c("only", "across")), step_increase = 0.08,
    map_signif_level = T, test = "wilcox.test", test.args=list(alternative = "two.side", paired = F),
    tip_length = c(0), color = "black", size = 0.2, textsize = 3
  )

p2


library(aplot)

p <- p1 %>%
  insert_top(p2, height=.3) 

p

```




```{r}

div <- qread("~/TCR_Dynamic/Fig/Fig2_p2/div_all.qs")

head(div)

div <- div %>%
  mutate(
    time = case_when(
      time == "pre" ~ "T1",
      time == "post" ~ "T2",
      TRUE ~ time
    )
  )

comp <- list(c("only", "across"))

div$status <- factor(div$status, levels = c("only", "across"))

div <- div %>%
  mutate(datasets = str_split(str_split(patient, "@", simplify = TRUE)[, 2], "_", simplify = TRUE)[, 1])


summary_dat <- div %>%  
group_by(type, time, status) %>%  
summarise(    Mean = mean(shannon),    
SE = sd(shannon)/sqrt(n())  )


p1 <- ggplot(data = summary_dat, aes(x=status, y=type, fill = Mean)) +
geom_tile(linewidth = 0.15, alpha = 0.9) +
geom_text(aes(label = sprintf("%.2f", Mean)), color = "black", size = 2) +
scale_fill_gradientn(
        colors = rev(c("#e59f24", "white","#57acaa"))) +
facet_grid( ~ time, scales = "fixed") +
ggtitle("") +
theme_minimal() +
theme(
    text = element_text(size = 6,  color = "black"),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    axis.title.x = element_text(size = 9,  color = "black"),
    axis.title.y = element_text(size = 9,  color = "black"),
    axis.text.x = element_text(size = 8,  color = "black"),
    axis.text.y = element_text(size = 9,  color = "black"),
    #legend.title = element_text(angle = 90, hjust = 0.5),
    panel.border = element_rect(color = "black", fill = NA, linewidth = .2),
    # panel.border = element_rect(color = "black", fill = NA, linewidth = 0.2),
    strip.text.x = element_text(size = 9, colour = "black"),
    strip.background = element_rect(color = "white", fill = "white"),
    axis.ticks.x=element_blank(),
    axis.ticks.y=element_blank(),
    axis.line = element_line(linewidth = 0.1),  ~
    axis.ticks = element_line(linewidth = 0.1), 
    legend.position = "right",
    panel.grid=element_blank())+
        coord_fixed() 

p1

summary_dat <- div %>%  
group_by(time, status) %>%  
summarise(    Mean = mean(shannon),    
SE = sd(shannon)/sqrt(n())  )


p2 <- ggplot() +  
geom_bar(data = div, aes(x = status, y = as.numeric(shannon), color = status), stat = "summary", fun = "mean", fill = "white", linewidth = 0.2, width = 0.8 ) +  
geom_point(data = div, aes(x = status, y = as.numeric(shannon), color = status), position = position_jitterdodge(0.95), alpha = 0.6, size = 1, stroke = NA, shape = 19)+ 
geom_errorbar(data = summary_dat, aes(x = status, ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.1, color = "black") +
scale_y_continuous(expand = c(0, 0)) +  
scale_color_manual(values = c("#e59f24", "#57acaa")) +  
facet_wrap(~ time, ncol = 12, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "TCR Ratio",
    color = "time status"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  ~
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "none",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) +
  geom_signif(data = div, aes(x = status, y = as.numeric(shannon)),
    comparisons = list(c("only", "across")), step_increase = 0.08,
    map_signif_level = T, test = "wilcox.test", test.args=list(alternative = "two.side", paired = T),
    tip_length = c(0), color = "black", size = 0.2, textsize = 3
  )

p2


p <- p1 %>%
  insert_top(p2, height=.3) 

p



```


```{r}


clonality <- qread("~/TCR_Dynamic/Fig/Fig2_p2/clonality_all_1016.qs")

head(clonality)

comp <- list(c("only", "across"))

clonality <- clonality %>%
  mutate(
    time = case_when(
      time == "pre" ~ "T1",
      time == "post" ~ "T2",
      TRUE ~ time
    )
  )


clonality <- subset(clonality, patient != "WZF")

clonality$status <- factor(clonality$status, levels = c("only", "across"))

clonality <- subset(clonality, clonality > 0)

summary_dat <- clonality %>%  
group_by(type, time, status) %>%  
summarise(    Mean = mean(clonality),    
SE = sd(clonality)/sqrt(n())  )


p1 <- ggplot(data = summary_dat, aes(x=status, y=type, fill = Mean)) +
geom_tile(linewidth = 0.15, alpha = 0.9) +
geom_text(aes(label = sprintf("%.2f", Mean)), color = "black", size = 2) +
scale_fill_gradientn(
        colors = rev(c("#e59f24", "white","#57acaa"))) +
facet_grid( ~ time, scales = "fixed") +
ggtitle("") +
theme_minimal() +
theme(
    text = element_text(size = 6,  color = "black"),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    axis.title.x = element_text(size = 9,  color = "black"),
    axis.title.y = element_text(size = 9,  color = "black"),
    axis.text.x = element_text(size = 8,  color = "black"),
    axis.text.y = element_text(size = 9,  color = "black"),
    #legend.title = element_text(angle = 90, hjust = 0.5),
    panel.border = element_rect(color = "black", fill = NA, linewidth = .2),
    # panel.border = element_rect(color = "black", fill = NA, linewidth = 0.2),
    strip.text.x = element_text(size = 9, colour = "black"),
    strip.background = element_rect(color = "white", fill = "white"),
    axis.ticks.x=element_blank(),
    axis.ticks.y=element_blank(),
    axis.line = element_line(linewidth = 0.1),  ~
    axis.ticks = element_line(linewidth = 0.1), 
    legend.position = "right",
    panel.grid=element_blank())+
        coord_fixed() #+
        # coord_flip()

p1


summary_dat <- clonality %>%  
group_by(time, status) %>%  
summarise(    Mean = mean(clonality),    
SE = sd(clonality)/sqrt(n())  )


p2 <- ggplot() +  
geom_bar(data = clonality, aes(x = status, y = as.numeric(clonality), color = status), stat = "summary", fun = "mean", fill = "white", linewidth = 0.2, width = 0.8 ) +  
geom_point(data = clonality, aes(x = status, y = as.numeric(clonality), color = status), position = position_jitterdodge(0.95), alpha = 0.6, size = 1, stroke = NA, shape = 19)+ 
geom_errorbar(data = summary_dat, aes(x = status, ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.1, color = "black") +
scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1)) +  
scale_color_manual(values = c("#e59f24", "#57acaa")) +  
facet_wrap(~ time, ncol = 12, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "TCR Ratio",
    color = "time status"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  ~
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "right",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) +
  geom_signif(data = clonality, aes(x = status, y = as.numeric(clonality)),
    comparisons = list(c("only", "across")), step_increase = 0.08,
    map_signif_level = T, test = "wilcox.test", test.args=list(alternative = "two.side", paired = F),
    tip_length = c(0), color = "black", size = 0.2, textsize = 3
  )

p2


p <- p1 %>%
  insert_top(p2, height=.3) 


p


```