
```{r}
rm(list = ls())

library(vegan)
library(dplyr)
library(tidyr)
library(stringr)
library(reshape2)
library(ggplot2)
library(ggsignif)
library(patchwork)
library(qs)


'%ni%'=Negate('%in%')

setwd("~/TCR_Dynamic/Fig/Fig2_p1/")

mycol <- c("#D62728", "#1F77B4",  "#FF7F0E", "#2CA02C", "#9467BD", "#8C564B", "#E377C2", "#BCBD22", "#17BECF", "#FF9896", "#AEC7E8", "#FFBB78", "#98DF8A",  "#C5B0D5",  "#C49C94",  "#F7B6D2", "#7F7F7F", "#DBDB8D", "#9EDAE5", "#45aab4","#fe7966","#81d0bb","#f9637c","#fbb45c","#038dT2","#FFDE99","#B8C8F5","#8fa2dc","#feaac2","#206491", "gold", "seagreen", "tomato", "#285d7c", "#f1d19e", "#e5807c", "#d7969a", "#eeebd8", "#d97d56", "#eecca9", "#eeeddb", "#494651", "#4b98a9", "#719eb6", "#679bc5", "#d94248", "#ebd66d", "#62985a", "#ecc832", "#e1a34e", "#ac3241", "#f5812d", "#d63833", "#ef5a30")


```


```{r}


pat_status <- qread("~/TCR_Dynamic/Fig/Fig2_p1/pat_status.qs")

head(pat_status)

comp <- list(c("only", "across"))



pat_status <- pat_status %>%
  mutate(datasets = str_split(str_split(patient, "@", simplify = TRUE)[, 2], "_", simplify = TRUE)[, 1])


summary_dat <- pat_status %>%  
# group_by(time, status) %>%  
group_by(datasets, time, status) %>%  
summarise(    Mean = mean(proportion),    
SE = sd(proportion)/sqrt(n())  )

summary_dat



p <- ggplot() +  
geom_bar(data = pat_status, aes(x = status, y = as.numeric(proportion), color = status), stat = "summary", fun = "mean", fill = "white", linewidth = 0.2, width = 0.8 ) +  
geom_point(data = pat_status, aes(x = status, y = as.numeric(proportion), color = status), position = position_jitterdodge(0.95), alpha = 0.6, size = 1, stroke = NA, shape = 19)+ 
geom_errorbar(data = summary_dat, aes(x = status, ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.1, color = "black") +
scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1)) +  
scale_color_manual(values = c("#e59f24", "#57acaa")) +  
facet_wrap(datasets ~ time, ncol = 6, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "TCR Ratio",
    color = "time status"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "top",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) +
  geom_signif(data = pat_status, aes(x = status, y = as.numeric(proportion)),
    comparisons = list(c("only", "across")), step_increase = 0.08,
    map_signif_level = T, test = "wilcox.test", test.args=list(alternative = "two.side", paired = T),
    tip_length = c(0), color = "black", size = 0.2, textsize = 3
  )

p


```



```{r}


ex_data <- qread("/home/xumeng/TCR_Dynamic/Fig/Fig2_p1/ex_data_1.5median_1016.qs")

head(ex_data)

comp <- list(c("only", "across"))



ex_data <- ex_data %>%
  mutate(datasets = str_split(str_split(patient, "@", simplify = TRUE)[, 2], "_", simplify = TRUE)[, 1])

ex_data <- subset(ex_data, expansion == "ex")

summary_dat <- ex_data %>%  
group_by(datasets, time, status) %>%  
summarise(    Mean = mean(proportion),    
SE = sd(proportion)/sqrt(n())  )

summary_dat

# head(summary_dat)

p <- ggplot() +  
geom_bar(data = ex_data, aes(x = status, y = as.numeric(proportion), color = status), stat = "summary", fun = "mean", fill = "white", linewidth = 0.2, width = 0.8 ) +  
geom_point(data = ex_data, aes(x = status, y = as.numeric(proportion), color = status), position = position_jitterdodge(0.95), alpha = 0.6, size = 1, stroke = NA, shape = 19)+ 
geom_errorbar(data = summary_dat, aes(x = status, ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.1, color = "black") +
scale_y_continuous(expand = c(0, 0), limits = c(0, 0.8)) +  
scale_color_manual(values = c("#e59f24", "#57acaa")) +  
facet_wrap(datasets ~ time, ncol = 6, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "Ex TCR Ratio",
    color = "time status"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "top",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) +
  geom_signif(data = ex_data, aes(x = status, y = as.numeric(proportion)),
    comparisons = list(c("only", "across")), step_increase = 0.08,
    map_signif_level = T, test = "wilcox.test", test.args=list(alternative = "two.side", paired = T),
    tip_length = c(0), color = "black", size = 0.2, textsize = 3
  )

p


```




```{r}


NI_shannon <- qread("/home/xumeng/TCR_Dynamic/Fig/Fig2_p1/div_1016.qs")

head(NI_shannon)

comp <- list(c("only", "across"))



NI_shannon <- NI_shannon %>%
  mutate(datasets = str_split(str_split(patient, "@", simplify = TRUE)[, 2], "_", simplify = TRUE)[, 1])


summary_dat <- NI_shannon %>%  
group_by(datasets, time, status) %>%  
summarise(    Mean = mean(shannon),    
SE = sd(shannon)/sqrt(n())  )

summary_dat

p <- ggplot() +  
geom_bar(data = NI_shannon, aes(x = status, y = as.numeric(shannon), color = status), stat = "summary", fun = "mean", fill = "white", linewidth = 0.2, width = 0.8 ) +  
geom_point(data = NI_shannon, aes(x = status, y = as.numeric(shannon), color = status), position = position_jitterdodge(0.95), alpha = 0.6, size = 1, stroke = NA, shape = 19)+ 
geom_errorbar(data = summary_dat, aes(x = status, ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.1, color = "black") +
scale_color_manual(values = c("#e59f24", "#57acaa")) +  
facet_wrap(datasets ~ time, ncol = 6, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "TCR Diversity",
    color = "time status"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "top",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) +
  geom_signif(data = NI_shannon, aes(x = status, y = as.numeric(shannon)),
    comparisons = list(c("only", "across")), step_increase = 0.08,
    map_signif_level = T, test = "wilcox.test", test.args=list(alternative = "two.side", paired = F),
    tip_length = c(0), color = "black", size = 0.2, textsize = 3
  )+
  coord_cartesian(ylim = c(5, NA))  

p


```




```{r}


index_df_1 <- qread("/home/xumeng/TCR_Dynamic/Fig/Fig2_p1/clonality_1016.qs")

head(index_df_1)

comp <- list(c("only", "across"))



index_df_1 <- index_df_1 %>%
  mutate(datasets = str_split(str_split(patient, "@", simplify = TRUE)[, 2], "_", simplify = TRUE)[, 1])

summary_dat <- index_df_1 %>%  
group_by(datasets, time, status) %>%  
summarise(    Mean = mean(clonality),    
SE = sd(clonality)/sqrt(n())  )


p <- ggplot() +  
geom_bar(data = index_df_1, aes(x = status, y = as.numeric(clonality), color = status), stat = "summary", fun = "mean", fill = "white", linewidth = 0.2, width = 0.8 ) +  
geom_point(data = index_df_1, aes(x = status, y = as.numeric(clonality), color = status), position = position_jitterdodge(0.95), alpha = 0.6, size = 1, stroke = NA, shape = 19)+ 
geom_errorbar(data = summary_dat, aes(x = status, ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.1, color = "black") +
scale_color_manual(values = c("#e59f24", "#57acaa")) +  
scale_y_continuous(expand = c(0, 0), limits = c(0, 0.4)) +  
facet_wrap(datasets ~ time, ncol = 6, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "TCR Clonality",
    color = "time status"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "top",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) +
  geom_signif(data = index_df_1, aes(x = status, y = as.numeric(clonality)),
    comparisons = list(c("only", "across")), step_increase = 0.08,
    map_signif_level = T, test = "wilcox.test", test.args=list(alternative = "two.side", paired = T),
    tip_length = c(0), color = "black", size = 0.2, textsize = 3
  )

p


```


