
```{r}

rm(list = ls())

library(ggpmisc)
library(tidyr)
library(dplyr)
library(stringr)
library(reshape2)
library(ggsignif)
library(patchwork)
library(qs)
library(aplot)

'%ni%'=Negate('%in%')

setwd("/home/xumeng/TCR_Dynamic/Fig/Fig2_rep_bulk_sc/")

mycol <- c("#D62728", "#1F77B4",  "#FF7F0E", "#2CA02C", "#9467BD", "#8C564B", "#E377C2", "#BCBD22", "#17BECF", "#FF9896", "#AEC7E8", "#FFBB78", "#98DF8A",  "#C5B0D5",  "#C49C94",  "#F7B6D2", "#7F7F7F", "#DBDB8D", "#9EDAE5", "#45aab4","#fe7966","#81d0bb","#f9637c","#fbb45c","#038dW2","#FFDE99","#B8C8F5","#8fa2dc","#feaac2","#206491", "gold", "seagreen", "tomato", "#285d7c", "#f1d19e", "#e5807c", "#d7969a", "#eeebd8", "#d97d56", "#eecca9", "#eeeddb", "#494651", "#4b98a9", "#719eb6", "#679bc5", "#d94248", "#ebd66d", "#62985a", "#ecc832", "#e1a34e", "#ac3241", "#f5812d", "#d63833", "#ef5a30")

```


```{r}

status_ratio_rep_cp <- qread("/home/xumeng/TCR_Dynamic/NoisET/data_examples/status_ratio_rep_cp.qs")

head(status_ratio_rep_cp)

patient_ratio_rep <- qread("/home/xumeng/TCR_Dynamic/NoisET/data_examples/patient_ratio.qs")

head(patient_ratio_rep)

rep_only <- left_join(status_ratio_rep_cp[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], patient_ratio_rep[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], by = "patient")

colnames(rep_only) <- c("po_ds", "eg_ds", "patient", "po", "eg")

head(rep_only)

rep_only$Type <- "rep"


```


```{r}

status_ratio_multi_cp <- qread("/home/xumeng/TCR_Dynamic/tissue_comp/new/status_ratio_multitissue_cp.qs")

head(status_ratio_multi_cp)

patient_ratio_multi <- qread("/home/xumeng/TCR_Dynamic/tissue_comp/patient_ratio_new.qs")

head(patient_ratio_multi)

multi_only <- left_join(status_ratio_multi_cp[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], patient_ratio_multi[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], by = "patient")

colnames(multi_only) <- c("po_ds", "eg_ds", "patient", "po", "eg")

head(multi_only)

multi_only$Type <- "sc"


```


```{r}

status_ratio_othersc_cp <- qread("/home/xumeng/TCR_Dynamic/randomicity/others_sc/status_ratio_othersc_cp.qs")

head(status_ratio_othersc_cp)

status_ratio_othersc_ncp <- qread("/home/xumeng/TCR_Dynamic/randomicity/others_sc/status_ratio_othersc_orig.qs")

head(status_ratio_othersc_ncp)


othersc_only <- left_join(status_ratio_othersc_cp[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], status_ratio_othersc_ncp[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], by = "patient")

colnames(othersc_only) <- c("po_ds", "eg_ds", "patient", "po", "eg")

head(othersc_only)

othersc_only$Type <- "sc"


```


```{r}

status_ratio_allbulk_cp <- qread("/home/xumeng/TCR_Dynamic/NoisET/data_examples/status_ratio_bulk_time_cp.qs")

head(status_ratio_allbulk_cp)

unique(status_ratio_allbulk_cp$patient) %>% length()

patient_ratio_rep <- qread("/home/xumeng/TCR_Dynamic/NoisET/data_examples/patient_ratio.qs")

head(patient_ratio_rep)

allbulk_only <- left_join(status_ratio_allbulk_cp[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], patient_ratio_rep[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], by = "patient")

colnames(allbulk_only) <- c("po_ds", "eg_ds", "patient", "po", "eg")

head(allbulk_only)

allbulk_only$Type <- "bulk"

dim(allbulk_only)


```




```{r}

all_only <- bind_rows(rep_only, multi_only, othersc_only, allbulk_only )

head(all_only)

table(all_only$Type)

ts4box_long <- all_only %>%
  gather(key = "status", value = "Ratio", po, eg, po_ds, eg_ds)

head(ts4box_long)

ts4box_long$status <- factor(ts4box_long$status, levels = c("po","eg", "po_ds", "eg_ds"))


p2 <- ggplot(subset(ts4box_long, status %in% c("po", "eg")), aes(x = status, y = as.numeric(Ratio), color = status)) +
      geom_point(aes(color = status), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      ggtitle("") +
      labs(
        x = NULL, y = "TCR Ratio",
        fill = "Tissue"
      ) +
      theme_classic() +
      facet_wrap(~ Type, scales = "free", ncol = 3) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("po","eg")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )

p2




p2 <- ggplot(subset(ts4box_long, status %in% c("po_ds", "eg_ds")), aes(x = status, y = as.numeric(Ratio), color = status)) +
      geom_point(aes(color = status), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      ggtitle("") +
      labs(
        x = NULL, y = "TCR Ratio",
        fill = "Tissue"
      ) +
      theme_classic() +
      facet_wrap(~ Type, scales = "free", ncol = 3) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("po_ds","eg_ds")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )

p2



```


```{r}

status_ratio_rep_cp <- qread("/home/xumeng/TCR_Dynamic/NoisET/data_examples/status_ratio_rep_cp.qs")

head(status_ratio_rep_cp)

patient_ratio_rep <- qread("/home/xumeng/TCR_Dynamic/NoisET/data_examples/patient_ratio.qs")

head(patient_ratio_rep)

rep_only <- left_join(status_ratio_rep_cp[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], patient_ratio_rep[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], by = "patient")

colnames(rep_only) <- c("po_ds", "eg_ds", "patient", "po", "eg")

head(rep_only)

rep_only$Type <- "rep"


```


```{r}

status_ratio_multi_cp <- qread("/home/xumeng/TCR_Dynamic/tissue_comp/new/status_ratio_multitissue_cp.qs")

head(status_ratio_multi_cp)

patient_ratio_multi <- qread("/home/xumeng/TCR_Dynamic/tissue_comp/patient_ratio_new.qs")

head(patient_ratio_multi)

multi_only <- left_join(status_ratio_multi_cp[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], patient_ratio_multi[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], by = "patient")

colnames(multi_only) <- c("po_ds", "eg_ds", "patient", "po", "eg")

head(multi_only)

multi_only$Type <- "ICB_sc"


```


```{r}

status_ratio_othersc_cp <- qread("/home/xumeng/TCR_Dynamic/randomicity/others_sc/status_ratio_othersc_cp.qs")

head(status_ratio_othersc_cp)

status_ratio_othersc_ncp <- qread("/home/xumeng/TCR_Dynamic/randomicity/others_sc/status_ratio_othersc_orig.qs")

head(status_ratio_othersc_ncp)


othersc_only <- left_join(status_ratio_othersc_cp[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], status_ratio_othersc_ncp[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], by = "patient")

colnames(othersc_only) <- c("po_ds", "eg_ds", "patient", "po", "eg")

head(othersc_only)

unique(othersc_only$patient)


othersc_only <- othersc_only %>%
  mutate(
    Type = case_when(
      patient %in% c("P1", "P3", "P8") ~ "Lung_Trans",
      patient %in% c("WZF",  "BFY", "XZH" ,  "ZBC") ~ "SBRT",
      TRUE ~ "TLGLL"

    )
  )


```


```{r}

status_ratio_allbulk_cp <- qread("/home/xumeng/TCR_Dynamic/NoisET/data_examples/status_ratio_bulk_time_cp.qs")

head(status_ratio_allbulk_cp)

unique(status_ratio_allbulk_cp$patient) %>% length()

patient_ratio_rep <- qread("/home/xumeng/TCR_Dynamic/NoisET/data_examples/patient_ratio.qs")

head(patient_ratio_rep)

allbulk_only <- left_join(status_ratio_allbulk_cp[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], patient_ratio_rep[, c("po_TCR_ratio", "eg_TCR_ratio", "patient")], by = "patient")

colnames(allbulk_only) <- c("po_ds", "eg_ds", "patient", "po", "eg")

head(allbulk_only)

unique(allbulk_only$patient)

unique(allbulk_only$patient)[grepl("SARS2", unique(allbulk_only$patient))]

allbulk_only <- allbulk_only %>%
  mutate(
    Type = case_when(
      patient %in% unique(allbulk_only$patient)[grepl("SARS2", unique(allbulk_only$patient))] ~ "Infection",
      patient %in% unique(allbulk_only$patient)[grepl("YT", unique(allbulk_only$patient))] ~ "Infection",
      patient %in% unique(allbulk_only$patient)[grepl("HCL", unique(allbulk_only$patient))] ~ "Health",
      patient %in% unique(allbulk_only$patient)[grepl("HCD", unique(allbulk_only$patient))] ~ "Health",
      TRUE ~ "ICB_bulk"

    )
  )


# allbulk_only$Type <- "bulk"



```


```{r}

all_only <- bind_rows(rep_only, multi_only, othersc_only, allbulk_only )

head(all_only)

table(all_only$Type)

ts4box_long <- all_only %>%
  gather(key = "status", value = "Ratio", po, eg, po_ds, eg_ds)

head(ts4box_long)

ts4box_long$status <- factor(ts4box_long$status, levels = c("po","eg", "po_ds", "eg_ds"))


p2 <- ggplot(subset(ts4box_long, status %in% c("po", "eg")), aes(x = status, y = as.numeric(Ratio), color = status)) +
      geom_point(aes(color = status), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      ggtitle("") +
      labs(
        x = NULL, y = "TCR Ratio",
        fill = "Tissue"
      ) +
      theme_classic() +
      facet_wrap(~ Type, scales = "fixed", ncol = 4) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("po","eg")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )

p2




p2 <- ggplot(subset(ts4box_long, status %in% c("po_ds", "eg_ds")), aes(x = status, y = as.numeric(Ratio), color = status)) +
      geom_point(aes(color = status), position = position_jitterdodge(0.9), alpha = 0.7, stroke = NA, shape = 19)+
  scale_size(range = c(0.2, 3), name = "T2") +
      stat_summary(fun.y = median, geom = 'crossbar', width = 0.3, size = 0.1, color = 'black') +
  stat_summary(fun.data = function(x) median_hilow(x, 0.5), geom = 'errorbar', width = 0.2, size = 0.15, color = 'black') +
  scale_color_manual(values = c("#34689A", "#B2B2B2")) +
      # scale_y_continuous(breaks = seq(0, 1.2, 0.2)) +
      ggtitle("") +
      labs(
        x = NULL, y = "TCR Ratio",
        fill = "Tissue"
      ) +
      theme_classic() +
      facet_wrap(~ Type, scales = "fixed", ncol = 4) +
      theme(
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, color = "black"),
        axis.title.y = element_text(size = 9),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.2),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.4, "lines"),
        strip.background = element_rect(fill = "white", color = "white"),
        strip.text = element_text(size = 7, face = "bold", colour = "black"),
        legend.position = "bottom",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)
      ) +
      geom_signif(
        comparisons = list(c("po_ds","eg_ds")), step_increase = 0.1,
        map_signif_level = F, test = wilcox.test, test.args = list(alternative = "two.side", paired = T),
        tip_length = 0, color = "black", size = 0.2, textsize = 2
      )

p2


```

