```{r}

library(tidyr)
library(dplyr)
library(stringr)
library(reshape2)
library(ggsignif)
library(patchwork)
library(qs)

'%ni%'=Negate('%in%')

setwd("/home/xumeng/TCR_Dynamic/Fig/Fig2_simu1/")

mycol <- c("#D62728", "#1F77B4",  "#FF7F0E", "#2CA02C", "#9467BD", "#8C564B", "#E377C2", "#BCBD22", "#17BECF", "#FF9896", "#AEC7E8", "#FFBB78", "#98DF8A",  "#C5B0D5",  "#C49C94",  "#F7B6D2", "#7F7F7F", "#DBDB8D", "#9EDAE5", "#45aab4","#fe7966","#81d0bb","#f9637c","#fbb45c","#038db2","#FFDE99","#B8C8F5","#8fa2dc","#feaac2","#206491", "gold", "seagreen", "tomato", "#285d7c", "#f1d19e", "#e5807c", "#d7969a", "#eeebd8", "#d97d56", "#eecca9", "#eeeddb", "#494651", "#4b98a9", "#719eb6", "#679bc5", "#d94248", "#ebd66d", "#62985a", "#ecc832", "#e1a34e", "#ac3241", "#f5812d", "#d63833", "#ef5a30")

```


```{r}


all_bulk <- qread("/home/xumeng/TCR_Dynamic/Fig/Fig2_simu1/all_bulk_1018.qs")


head(all_bulk)

head(all_bulk)

summary_stats <- unique(all_bulk[, -c(3:4)]) %>%
  group_by(patient, time, Datasets) %>%
  summarise(
    n_rows = n(),                        
    sum_count = sum(count_bl, na.rm = TRUE)  
  )



write.csv(summary_stats, "Fig2_real_distre.csv")

```


```{r}

head(all_bulk)


all_bulk$count <- all_bulk$count_bl

all_bulk$sampleid <- paste0(all_bulk$patient, "@", all_bulk$time)

head(all_bulk)

quantiles <- subset(all_bulk, count > 0) %>%
group_by(sampleid, Datasets) %>%
  summarize(
    min = min(count),
    q10 = quantile(count, 0.1),
    q20 = quantile(count, 0.2),
    q30 = quantile(count, 0.3),
    q40 = quantile(count, 0.4),
    q50 = quantile(count, 0.5),
    q60 = quantile(count, 0.6),
    q70 = quantile(count, 0.7),
    q80 = quantile(count, 0.8),
    q90 = quantile(count, 0.9),
    q95 = quantile(count, 0.95),
    q975 = quantile(count, 0.975),
    q99 = quantile(count, 0.99),
    q995 = quantile(count, 0.995),
    q999 = quantile(count, 0.999),
    max = max(count),
  )


quantiles_table <- quantiles %>%
  mutate(across(where(is.numeric), round, digits = 2)) %>% 
  as.data.frame()

quantiles_table


average_df <- quantiles_table %>%
  group_by(Datasets) %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE))


print(average_df)


average_df <- average_df %>%
  pivot_longer(
    cols = -c(Datasets),
    names_to = "quantile",
    values_to = "value"
  )


head(average_df)

quantile_level <- unique(average_df$quantile)

quantile_level

average_df$quantile <- factor(average_df$quantile, levels = quantile_level)

library(ggsci)

p <- ggplot(subset(average_df, quantile %ni% c("q995", "q999") & Datasets != "HCD_pbmc"), aes(x = quantile, y = log2(value), group = Datasets, color = Datasets)) +
  geom_point(size = 1) +
  geom_line(linewidth = 0.2) +
  labs(x = "Quantile", y = "Log2(Clonosize)") +
  scale_color_manual(values = mycol)+
  theme_bw()+
  theme(
    plot.title = element_text(size = 8, color = "black", hjust = 0.5),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 6, color = "black"),
    axis.text.y = element_text(size = 6, color = "black"),
    axis.title.y = element_text(size = 7, color = "black"),
    axis.title.x = element_text(size = 7, color = "black"),
    axis.line = element_blank(),
    axis.ticks = element_line(linewidth = 0.2),
    panel.grid = element_line(linewidth = 0.2),
    legend.position = "right",
    legend.text = element_text(size = 6),
    legend.title = element_text(size = 7),
  )


p


```
