
```{r}

rm(list=ls())

library(ggpmisc)
library(tidyr)
library(dplyr)
library(stringr)
library(reshape2)
library(ggsignif)
library(patchwork)
library(qs)
library(aplot)
library(forestmodel)
library(survival)

setwd("/home/xumeng/TCR_Dynamic/Fig/Fig2_Factor")

```


```{r}

patient_ratio <- qread("/home/xumeng/TCR_Dynamic/Fig/Fig2_Factor/patient_ratio_1020.qs")

```

```{r}


data4po <- patient_ratio[, c("patient","po_TCR_ratio", "T1_TCell", "T1_TCR","T1_TCell_pct",  "T1_TCR_pct", "T1_T2_TCell", "T1_T2_TCR","T1_clonality", "T1_div","depth")] %>% unique()


df <- data4po 

head(data4po)

vars_needed <- c("po_TCR_ratio", "T1_TCR_pct", "T1_T2_TCR", "T1_clonality", "depth")

dfm <- df[complete.cases(df[, vars_needed]), vars_needed]

dfm$T1_T2_TCR_s   <- as.numeric(scale(dfm$T1_T2_TCR))
dfm$depth_s       <- as.numeric(scale(dfm$depth))

adjust01 <- function(y) {
  n <- length(y)
  (y * (n - 1) + 0.5) / n
}

dfm$po_TCR_ratio_bounded <- pmin(pmax(dfm$po_TCR_ratio, 0), 1)
dfm$po_TCR_ratio_adj <- adjust01(dfm$po_TCR_ratio_bounded)

```


```{r}

library(forestmodel)
library(dplyr)


model_formula <- as.formula(
  "po_TCR_ratio ~ T1_TCR_pct + T1_T2_TCR + T1_clonality + depth"
)
model <- lm(model_formula, data = data4po)


coef(summary(model))[, 4]

p_adj <- p.adjust(coef(summary(model))[, 4][2:5], method = "BH")

p_adj



forest.panels <- list(
  list(width = 0.02), 
  list(width = 0.18, display = ~variable, fontface = "bold", heading = "Variable"),
  list(width = 0.10, display = ~level),
  list(width = 0.02, item = "vline", hjust = 0.5),
  list(
    width = 0.35, item = "forest", hjust = 0.5,
    heading = "Effect size (β ± 95% CI)",
    linetype = "dashed", line_x = 0,
    point_size = 1.5  
  ),
  list(width = 0.02, item = "vline", hjust = 0.5),
  list(width = 0.18,
       display = ~sprintf("%0.3f (%0.3f, %0.3f)",
                          estimate, conf.low, conf.high),
       hjust = 0),
  list(width = 0.18,
       display = ~ifelse(reference, "", format.pval(p.value, digits = 1, eps = 0.001)),
       heading = "p", hjust = 0.5)
)


forest_model(
  model,
  panels = forest.panels,
  factor_separate_line = FALSE
)

 
pdf("Po_TCR_ratio_Forest_refined.pdf", width = 8, height = 3)
print(forest_model(
  model,
  panels = forest.panels,
  factor_separate_line = FALSE
))
dev.off()



```




```{r}

data4eg <- patient_ratio[, c("patient","eg_TCR_ratio",  "T2_TCell", "T2_TCell_pct", "T2_TCR", "T2_TCR_pct", "T2_T1_TCell", "T2_T1_TCR", "T2_div", "T2_clonality", "depth")] %>% unique()


model_formula <- as.formula(
  "eg_TCR_ratio ~ T2_TCR_pct + T2_T1_TCR + T2_clonality + depth"
)


model <- lm(model_formula, data = data4eg)

summary(model)

coef(summary(model))[, 4]

p_adj <- p.adjust(coef(summary(model))[, 4][2:5], method = "BH")

p_adj


forest.panels <- list(
  list(width = 0.02), 
  list(width = 0.18, display = ~variable, fontface = "bold", heading = "Variable"),
  list(width = 0.10, display = ~level),
  list(width = 0.02, item = "vline", hjust = 0.5),
  list(
    width = 0.35, item = "forest", hjust = 0.5,
    heading = "Effect size (β ± 95% CI)",
    linetype = "dashed", line_x = 0,
    point_size = 1.5  # 缩小点的大小（默认约 4）
  ),
  list(width = 0.02, item = "vline", hjust = 0.5),
  list(width = 0.18,
       display = ~sprintf("%0.3f (%0.3f, %0.3f)",
                          estimate, conf.low, conf.high),
       hjust = 0),
  list(width = 0.18,
       display = ~ifelse(reference, "", format.pval(p.value, digits = 1, eps = 0.001)),
       heading = "p", hjust = 0.5)
)


forest_model(
  model,
  panels = forest.panels,
  factor_separate_line = FALSE
)

pdf("Eg_TCR_ratio_Forest_refined.pdf", width = 8, height = 3)
print(forest_model(
  model,
  panels = forest.panels,
  factor_separate_line = FALSE
))
dev.off()



```

