
```{r}

library(tidyr)
library(dplyr)
library(stringr)
library(reshape2)
library(ggsignif)
library(patchwork)
library(qs)


'%ni%'=Negate('%in%')

setwd("~/TCR_Dynamic/sc_vs_bulk/")

mycol <- c("#D62728", "#1F77B4",  "#FF7F0E", "#2CA02C", "#9467BD", "#8C564B", "#E377C2", "#BCBD22", "#17BECF", "#FF9896", "#AEC7E8", "#FFBB78", "#98DF8A",  "#C5B0D5",  "#C49C94",  "#F7B6D2", "#7F7F7F", "#DBDB8D", "#9EDAE5", "#45aab4","#fe7966","#81d0bb","#f9637c","#fbb45c","#038dpost","#FFDE99","#B8C8F5","#8fa2dc","#feaac2","#206491", "gold", "seagreen", "tomato", "#285d7c", "#f1d19e", "#e5807c", "#d7969a", "#eeebd8", "#d97d56", "#eecca9", "#eeeddb", "#494651", "#4b98a9", "#719eb6", "#679bc5", "#d94248", "#ebd66d", "#62985a", "#ecc832", "#e1a34e", "#ac3241", "#f5812d", "#d63833", "#ef5a30")

```


```{r}

BCC_pair_all_count <- read.csv("~/TCR_Dynamic/sc_vs_bulk/BCC/BCC_pair_all_count.csv")

BCC_pair_all_count$tissue <- "Tumor"

HN_PBMC_pair_all_count <- read.csv("~/TCR_Dynamic/sc_vs_bulk/HN/PBMC/HN_PBMC_pair_all_count.csv")

HN_PBMC_pair_all_count$tissue <- "PBMC"


HN_tumor_pair_all_count <- read.csv("~/TCR_Dynamic/sc_vs_bulk/HN/Tumor/HN_tumor_pair_all_count.csv")

HN_tumor_pair_all_count$tissue <- "Tumor"


pair_all_count <- bind_rows(BCC_pair_all_count, HN_PBMC_pair_all_count, HN_tumor_pair_all_count)

pair_all_count


write.csv(pair_all_count, "pair_all_count.csv")


pair_all_count <- read.csv("~/TCR_Dynamic/sc_vs_bulk/pair_all_count.csv")

table(pair_all_count$seqtype)

length(unique(pair_all_count$patient))


```


```{r}

status_change_all_BCC_Tumor <- qread("~/TCR_Dynamic/sc_vs_bulk/BCC/status_change_all_BCC_Tumor.qs")

status_change_all_HN_PBMC <- qread("~/TCR_Dynamic/sc_vs_bulk/HN/PBMC/status_change_all_HN_PBMC_new.qs")

status_change_all_HN_Tumor <- qread("~/TCR_Dynamic/sc_vs_bulk/HN/Tumor/status_change_all_HN_Tumor.qs")

status_change_all_BCC_Tumor$datasets <- "BCC_Tumor"
status_change_all_HN_PBMC$datasets <- "HN_PBMC"
status_change_all_HN_Tumor$datasets <- "HN_Tumor"


status_change_all <- bind_rows(status_change_all_BCC_Tumor, status_change_all_HN_PBMC, status_change_all_HN_Tumor)

status_change_all <- status_change_all %>%
  mutate(
    status_sc = case_when(
      status_sc == "pre-only" ~ "pre_only",
      status_sc == "pre-existing" ~ "pre_existing",
      TRUE ~ status_sc
    )
  )


head(status_change_all)



```




```{r}

comp <- list(c("pre_only", "pre_existing"), c("emergent", "pre_existing"), c("emergent", "pre_only"))

head(status_change_all)

table(status_change_all$status_sc)
table(status_change_all$status_bulk)

status_change_all <- subset(status_change_all, status_bulk != "sc_only")

status_change_all$status_sc <- factor(status_change_all$status_sc, levels = c("pre_only", "pre_existing", "emergent"))

status_change_all$status_bulk <- factor(status_change_all$status_bulk, levels = c("pre_only", "pre_existing", "emergent"))

p1 <- ggplot(status_change_all, aes(x = status_sc, y = as.numeric(percent), color = status_sc)) +
  geom_boxplot(alpha = 0.4, outliers = F, linewidth = 0.2) + 
  scale_fill_manual(values = c("#DA5819", "#03A09C", "#5C618D")) + 
geom_point(position = position_jitterdodge(0.95), alpha = 0.9, size = 1.2, stroke = NA, shape = 19)+
scale_color_manual(values = c("#41549d", "#569357", "#ddbc58")) + 
facet_grid(datasets ~ status_bulk, scales = "free") +
    scale_y_continuous(breaks = seq(0,100,25)) + 

  labs(
    title = "",
    x = "",
    y = "TCR Ratio",
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=8, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=9, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "right",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) +
  geom_signif(
    comparisons = comp, step_increase = 0.1,
    map_signif_level = T, test = wilcox.test, test.args=list(alternative = "two.side", paired = T),
    tip_length = c(0), color = "black", size = 0.2, textsize = 2
  )

p1

getwd()




p1 <- ggplot(status_change_all, aes(x = status_sc, y = as.numeric(percent), color = status_sc)) +
  geom_boxplot(alpha = 0.4, outliers = F, linewidth = 0.2) + 
  scale_fill_manual(values = c("#DA5819", "#03A09C", "#5C618D")) + 
geom_point(position = position_jitterdodge(0.95), alpha = 0.9, size = 1.2, stroke = NA, shape = 19)+
scale_color_manual(values = c("#41549d", "#569357", "#ddbc58")) + 
facet_grid(~ status_bulk, scales = "fixed") +
    scale_y_continuous(breaks = seq(0,100,25)) + 
  labs(
    title = "",
    x = "",
    y = "TCR Ratio",
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=8, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=9, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2), 
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "right",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) +
  geom_signif(
    comparisons = comp, step_increase = 0.1,
    map_signif_level = T, test = wilcox.test, test.args=list(alternative = "two.side", paired = T),
    tip_length = c(0), color = "black", size = 0.2, textsize = 2
  )

p1


```


```{r}

head(status_change_all)

status_change_all <- subset(status_change_all, status_bulk != "sc_only")

tatus_summary <- status_change_all %>%
  group_by(status_bulk, status_sc) %>%
  summarise(total_freq = sum(Freq), .groups = "drop")

head(tatus_summary)


p1 <- ggplot(data = tatus_summary, aes(status_bulk, status_sc, fill = total_freq)) +
geom_tile(linewidth = 0.15, alpha = 0.8) +
geom_text(aes(label = sprintf("%.f", total_freq)), color = "black", size = 3) +
scale_fill_gradientn(
        ## limits = c(-1.5, 1.5),
        colors = c("#9fb9bc", "white", "#EF7B30")) +
ggtitle("") +
theme_minimal() +
theme(
    text = element_text(size = 6,  color = "black"),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    axis.title.x = element_text(size = 9,  color = "black"),
    axis.title.y = element_text(size = 9,  color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 8,  color = "black"),
    axis.text.y = element_text(size = 9,  color = "black"),
    #legend.title = element_text(angle = 90, hjust = 0.5),
    panel.border = element_rect(color = "black", fill = NA, linewidth = .2),
    # panel.border = element_rect(color = "black", fill = NA, linewidth = 0.2),
    strip.text.x = element_text(size = 9, colour = "black"),
    strip.background = element_rect(color = "white", fill = "white"),
    axis.ticks.x=element_blank(),
    axis.ticks.y=element_blank(),
    axis.line = element_line(linewidth = 0.1), 
    axis.ticks = element_line(linewidth = 0.1), 
    legend.position = "none",
    panel.grid=element_blank())+
        coord_fixed()

p1

```



