
# Clusters and Markers

## load packages and set work path

```{r}
rm(list = ls())

library(Seurat)
library(tidyr)
library(dplyr)
library(stringr)
library(reshape2)
library(ggplot2)
library(ggsignif)
library(patchwork)
library(qs)
library(aplot)

'%ni%'=Negate('%in%')

setwd("~/TCR_Dynamic/Fig/Fig1_Tcell/")

mycol <- c("#D62728", "#1F77B4",  "#FF7F0E", "#2CA02C", "#9467BD", "#8C564B", "#E377C2", "#BCBD22", "#17BECF", "#FF9896", "#AEC7E8", "#FFBB78", "#98DF8A",  "#C5B0D5",  "#C49C94",  "#F7B6D2", "#7F7F7F", "#DBDB8D", "#9EDAE5", "#45aab4","#fe7966","#81d0bb","#f9637c","#fbb45c","#038db2","#FFDE99","#B8C8F5","#8fa2dc","#feaac2","#206491", "gold", "seagreen", "tomato", "#285d7c", "#f1d19e", "#e5807c", "#d7969a", "#eeebd8", "#d97d56", "#eecca9", "#eeeddb", "#494651", "#4b98a9", "#719eb6", "#679bc5", "#d94248", "#ebd66d", "#62985a", "#ecc832", "#e1a34e", "#ac3241", "#f5812d", "#d63833", "#ef5a30")


```

## load data 

```{r}

td <- qread("~/TCR_Dynamic/ICB_T/clusters_analysis_2-1/td.qs", nthreads = 10)

head(td)

patients <- unique(td$pt)

patients


td@meta.data <- td@meta.data %>%
  mutate(response = case_when(
    patient %in% c("su001", "su002", "su003", "su004", "su009", "su012") & datasets == "BCC" ~ "R", # 
    patient %in% c("su005", "su006", "su007", "su008",  "su010") & datasets == "BCC" ~ "NR",

    patient %in% c("su010","su011") & datasets == "SCC" ~ "R",
    patient %in% c("su013", "su014") & datasets == "SCC" ~ "NR",

    patient %in% c("P001", "P002",  "P004", "P005", "P016","P017") & datasets == "BC_zhang" ~ "R",
    patient %in% c("P007", "P010", "P012", "P019") & datasets == "BC_zhang" ~ "NR",

    patient %in% c("P18_HN", "P32_HN") & datasets == "HN" ~ "R",
    patient %in% c("P24_HN", "P27_HN", "P29_HN") & datasets == "HN" ~ "NR",


    patient %in% c("P01", "P02", "P03", "P04", "P06", "P08") & datasets == "ESCC" ~ "R",
    patient %in% c("P05", "P07", "P09") & datasets == "ESCC" ~ "NR",


    patient %in% c("P01", "P04", "P08", "P11", "P12", "P15", "P17", "P18", "P19", "P20", "P22", "P23","P26", "P03", "P05", "P09", "P14", "P24") & datasets == "CRC" ~ "R",
    patient %in% c("P16","P25") & datasets == "CRC" ~ "NR",

    patient %in% c("P29", "P30", "P33", "P35") & datasets == "Lung" ~ "R",

    patient %in% c("Patient01",   "Patient02",   "Patient03T1", "Patient03T2", "Patient04",   "Patient05",   "Patient07" ,  "Patient09" ,  "Patient11" ,  "Patient12" ,  "Patient16",   "Patient18", "Patient19",   "Patient20",   "Patient23" ,  "Patient30" ,  "Patient42",   "Patient43" ,  "Patient46" ,  "Patient47" ,  "Patient48" ,  "Patient56" ,  "Patient63" ,  "Patient66") & datasets == "BC_Shiao" ~ "R",
    patient %in% c("Patient06", "Patient10", "Patient15", "Patient17", "Patient26", "Patient39", "Patient45", "Patient52", "Patient53", "Patient57", "Patient64") & datasets == "BC_Shiao" ~ "NR",

    TRUE ~ "no_data"  
  ))


td@meta.data <- td@meta.data %>%
  mutate(TCR = case_when(
    is.na(cdr3b) ~ "no_TCR",
    TRUE ~ "TCR"
  ))

table(td$TCR)

qsave(td@meta.data, "td_meta.qs", nthreads = 8)

td_TCR <- subset(td@meta.data, TCR == "TCR")

TCR_df <- table(td_TCR$sample) %>% as.data.frame()

mean(TCR_df$Freq)

# 1162.683

# table(td$clusters, td$TCR)

```

## Find Cluster's Markers

```{r, include=FALSE}

td <- NormalizeData(td, normalization.method = "LogNormalize", assay = "RNA", scale.factor = 10000)

mito_genes <- grep("^MT-", rownames(td), value = TRUE)
ribo_genes <- grep("^RP[LS]", rownames(td), value = TRUE)
orf_gene <- grep("*orf*", rownames(td), value = TRUE)
hsp_gene <- grep("^HSP", rownames(td), value = TRUE)
trv_gene <- grep("^TR[ABGD]V*", rownames(td), value = TRUE)

all_genes <- rownames(td)
genes_to_keep <- setdiff(all_genes, c(mito_genes, hsp_gene, ribo_genes, orf_gene, trv_gene))

Idents(td) <- 'clusters'

unique(td$clusters)

head(td)


unique(td$clusters)

global_DEGs <- FindAllMarkers(td, features = genes_to_keep, group.by = 'clusters', only.pos = TRUE)


library(GPTCelltype)

library(openai)

ct <- gptcelltype(global_DEGs, model = 'gpt-4')

print(ct)


clusters_markers <- global_DEGs %>%
  group_by(cluster) %>%
  # filter(avg_log2FC > 0.5) %>% 
  filter(p_val_adj < 0.01)

write.csv(clusters_markers, "CD8T_clusters_markers.csv")

td$clusters <- factor(td$clusters, levels = c("T1", "T2", "T3", "T4", "T5", "T6", "T7", "T8", "T9", "T10"))

show.genes <- c(
  "CD8A", "CD8B", "CD4", 
 "TCF7",  "CCR7", 
 "KLRB1", "SLC4A10",
 "GZMK", "EOMES",
 "XCL1", "ZNF683", 
 "GZMB",  "ITGAE", "LAG3", "PDCD1",
  "CXCL13", "RBPJ", "TNFRSF4",  
  "FOXP3", "CTLA4", "IL2RA", 
  "MKI67", "TYMS",
  "ISG15", "IFI6", 
  "FGFBP2", "FCGR3A"
  )



```

## Markers Plot
```{r, fig.height=16, fig.width=6}


p <- DotPlot(td, features = show.genes)

dat <- p$data

head(dat)

cluster.order <- c("T1", "T2", "T3", "T4", "T5", "T6", "T7", "T8", "T9", "T10")

p <- ggplot(dat, aes(features.plot, id, size=pct.exp, color=avg.exp.scaled)) + 
  geom_point(shape = 19, stroke=NA) +
  scale_size(range = c(0, 3)) +#, limits = c(0, 100), breaks = c(0,25,50,75,100))+  
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill=NA))) + 
  theme(
    panel.background = element_blank(),
    panel.border = element_rect(fill = NA),
    panel.grid.major.x = element_line(color = "grey80", linewidth = 0.001),
    panel.grid.major.y = element_line(color = "grey80", linewidth = 0.001),
    axis.line = element_blank(),
    axis.ticks = element_line(linewidth = 0.2), 
    axis.title = element_blank(),
    axis.text.y = element_text(color='black',size=6),
    axis.text.x = element_text(color='black',size=6, angle = 90, hjust = 1, vjust = 0.5),
    legend.position = "bottom",
    legend.text = element_text(size=6, color = "black"),
    legend.title = element_text(size=7, color = "black"),
    legend.key.size = unit(6, "pt")
    )+
  scale_color_gradientn(
        ## limits = c(-1.5, 1.5),
        colors = c("#9fb9bc", "white", "#EF7B30"))

p


# ggsave("cluster_markers_dot_new_1.pdf", p, width = 2.3, height = 2)

```


## Metadata on Umap
```{r}

source("~/R_package/ArchTCR/R/clonosize_umap.R")
# source("/home/xumeng/R_package/Integration/color_code.R")

str(td)


td@meta.data <- td@meta.data %>%
  mutate(clusters_new = case_when(
    clusters == "T1" ~ "C1",
    clusters == "T2" ~ "C2",
    clusters == "T3" ~ "C3",
    clusters == "T4" ~ "C4",
    clusters == "T5" ~ "C5",
    clusters == "T6" ~ "C6",
    clusters == "T7" ~ "C7",
    clusters == "T8" ~ "C8",
    clusters == "T9" ~ "C9",
    clusters == "T10" ~ "C10"

  ))


colors_use <- c('#fc8d59','#9e9ac8','#96daf7','#fed976','#b0479a','#35978f','#193a1c','#e31a1c','#f9d3d7','#08306b')

str(td)

p1 <- myumap_1(td, ident = "cell_types", cols = colors_use, Embedding = "umap", label = TRUE, label_ident = "clusters_new")


# ggsave("cluster_overview_2_new.png", p1, width = 3, height = 3, dpi = 600)

```



```{r}

color.code= c("grey80","#F1DF91", "#FBAD46", "#F36E21", "#C62832", "#8A1739", "#4B0E3D")

markers <- c("CD8A", "CD8B", "CD4")

feature.lst <- sapply(markers, function(gene){
    p <- FeaturePlot(td, features = gene, slot = "data", raster=TRUE,  order=TRUE, label.size = 6) +
          scale_color_gradientn(colors = colorRampPalette(color.code)(255)) +
          theme(legend.position = "none",
          axis.text = element_blank(),    
                axis.title = element_blank(),   
                axis.ticks = element_blank(),  
                axis.line = element_blank(),    
                panel.background = element_blank(),  
                panel.grid.major = element_blank(),  
                panel.grid.minor = element_blank())  
    return(p)
})

library(patchwork)

p3 <- wrap_plots(feature.lst, ncol = 1)

# ggsave("CD4_CD8_feature.pdf", p3, width = 2, height = 6)


```



```{r}

source("~/R_package/ArchTCR/R/integrate.R")
source("~/TCR_Dynamic/color.code.R")

ten_col <- c("#85a2d2", "#f9d580", "#2983b1", "#54beaa", "#A5C496", "#E79397",  "#eca680", "#7ac7e2",  "#7E9BB7",  "#bdb5e1", "#A797DA")

p <- batch_bar(td,
cluster = "clusters_new",
group = "datasets",
mycol = ten_col) 

p

# ggsave(paste0("clusters_", "datasets", "_bar.pdf"), p, width = 4.5, height = 3)

p <- batch_bar(td,
cluster = "clusters",
group = "TCR",
mycol = tcr_col) 

p

# ggsave(paste0("clusters_", "TCR", "_bar.pdf"), p, width = 4.5, height = 3)


p <- batch_bar(td,
cluster = "clusters",
group = "treatment",
mycol = time_col) 

p

# ggsave(paste0("clusters_", "treatment", "_bar.pdf"), p, width = 4.5, height = 3)


```



```{r}

head(td)

td <- qread("~/TCR_Dynamic/Fig/Fig1_Tcell/td_meta.qs")

patients <- unique(td$pt)

cell_count <- NULL


head(td)

samples <- unique(td$sample)

cell_count <- NULL

for (p in samples) {

td_tmp <- subset(td, sample == p)

cell_count_2 <- table(td_tmp$clusters) %>% as.data.frame()

colnames(cell_count_2) <- c("clusters", "count")

cell_count_2$sample <- p

cell_count_2$ratio <- cell_count_2$count / sum(cell_count_2$count)

cell_count <- rbind(cell_count, cell_count_2)

}

head(cell_count)

cell_count <- left_join(cell_count, unique(td[, c("sample", "treatment","response")]), by = "sample")

comp <- list(c("pre", "post"))

cell_count$treatment <- factor(cell_count$treatment, levels = c("pre", "post"))

library(ggsignif)

p <- ggplot2::ggplot(data = subset(cell_count, response != "no_data"), aes(x = treatment, y = as.numeric(ratio), color = treatment)) +
        geom_boxplot(outliers = FALSE, linewidth = 0.15) +
        geom_point(position = position_jitterdodge(0.95), alpha = 0.8, size = 0.8, stroke = NA, shape = 19)+
        facet_grid(response ~ clusters, scales = "fixed") +
        labs(x = '', y = "Fraction")+
        scale_color_manual(values = c("#8f8070", "#a54633")) +  
        theme_classic() +
        theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=8, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=9, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "right",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) +
geom_signif(
    comparisons = comp, step_increase = 0.1,
    map_signif_level = F, test = wilcox.test, test.args=list(alternative = "two.side", paired = T),
    tip_length = c(0), color = "black", size = 0.2, textsize = 2
  )


p

# ggsave("cell_ratio_change1_new.pdf", p, width = 6, height = 2)


comp_res <- list(c("R", "NR"))

head(cell_count)

p <- ggplot2::ggplot(data = subset(cell_count, response != "no_data"), aes(x = response, y = as.numeric(ratio), color = response)) +
        geom_boxplot(outliers = FALSE, linewidth = 0.1) +
        geom_point(position = position_jitterdodge(0.95), alpha = 0.6, size = 1, stroke = NA, shape = 19)+
        facet_grid(treatment ~ clusters, scales = "fixed") +
        labs(x = '', y = "Fraction")+
        scale_color_manual(values = c("#98989d", "#856e91")) +  
        theme_classic() +
        theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=8, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=9, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "right",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) +
geom_signif(
    comparisons = comp_res, step_increase = 0.1,
    map_signif_level = F, test = wilcox.test, test.args=list(alternative = "two.side", paired = F),
    tip_length = c(0), color = "black", size = 0.2, textsize = 2
  )


p

# ggsave("cell_ratio_change2.pdf", p, width = 6, height = 4)


```
