

```{r}

rm(list=ls())
library(Seurat)
library(tidyr)
library(dplyr)
library(stringr)
library(reshape2)
library(ggplot2)
library(ggsignif)
library(patchwork)
library(qs)
library(aplot)

'%ni%'=Negate('%in%')

setwd("/home/xumeng/TCR_Dynamic/Fig/Fig1_TCR/")

mycol <- c("#D62728", "#1F77B4",  "#FF7F0E", "#2CA02C", "#9467BD", "#8C564B", "#E377C2", "#BCBD22", "#17BECF", "#FF9896", "#AEC7E8", "#FFBB78", "#98DF8A",  "#C5B0D5",  "#C49C94",  "#F7B6D2", "#7F7F7F", "#DBDB8D", "#9EDAE5", "#45aab4","#fe7966","#81d0bb","#f9637c","#fbb45c","#038db2","#FFDE99","#B8C8F5","#8fa2dc","#feaac2","#206491", "gold", "seagreen", "tomato", "#285d7c", "#f1d19e", "#e5807c", "#d7969a", "#eeebd8", "#d97d56", "#eecca9", "#eeeddb", "#494651", "#4b98a9", "#719eb6", "#679bc5", "#d94248", "#ebd66d", "#62985a", "#ecc832", "#e1a34e", "#ac3241", "#f5812d", "#d63833", "#ef5a30")

source("/home/xumeng/TCR_Dynamic/color.code.R")

```


```{r}

td <- qread("/home/xumeng/TCR_Dynamic/ICB_T/clusters_analysis_2-1/td.qs", nthreads = 10)

head(td)

TCR <- qread("/home/xumeng/TCR_Dynamic/Fig/Fig1_TCR/ICB_sc_TCR_sample.qs")

head(TCR)

td@meta.data <- left_join(td@meta.data, TCR[, c(1,2,3,6)] , by = c("patient", "cdr3b", "datasets"))

rownames(td@meta.data) <- td$barcode_all

td_TCR <- subset(td, TCR == "TCR")

head(td_TCR)

td_TCR@meta.data <- td_TCR@meta.data %>%
  mutate(
    status_s = case_when(
      status == "pre-only" ~ "only",
      status == "emergent" ~ "only",
      status == "pre-existing" ~ "across",
      TRUE ~ "others"
    )
  )


dim(td_TCR)

table(td_TCR$status_s)

getwd()


qsave(td_TCR, "td_TCR_new.qs", nthreads = 12)


```


```{r}

head(td_TCR)

td_TCR$sid_clusters <- paste0(td_TCR$sample, "@", td_TCR$clusters)

source("~/R_package/ArchTCR/R/utilities.R")

td_TCR$TCR_size <- NULL 

td_TCR <- clonosize(sce = td_TCR, sample = "sid_clusters", tcr_call = "cdr3b")

td_TCR <- clonosize_rank(sce = td_TCR, clonosize = "clonotype_size")

source("~/R_package/ArchTCR/R/clonosize_umap.R")

td_TCR$treatment <- factor(td_TCR$treatment, levels = c("pre", "post"))



all_data <- subset(td_TCR, response != "no_data")$clonotype_size
all_data <- subset(td_TCR)$clonotype_size
global_min <- min(all_data, na.rm = TRUE)
global_max <- max(all_data, na.rm = TRUE)

color.code= c("grey80","#F1DF91", "#FBAD46", "#F36E21", "#C62832", "#8A1739", "#4B0E3D")


p1 <- FeaturePlot(subset(td_TCR, treatment == "pre" & cdr3b != "CASSDAGDTDTQYF"), features = "clonotype_size", slot = "data",  raster=TRUE,  order=TRUE) +
    scale_color_gradientn(trans = "log2", colors = color.code, limits = c(global_min, global_max)) +
    theme(legend.position = "right",
    axis.text = element_blank(),    
        axis.title = element_blank(),  
        axis.ticks = element_blank(),   
        axis.line = element_blank(),    
        panel.background = element_blank(),  
        panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank())  
p2 <- FeaturePlot(subset(td_TCR, treatment == "post" & cdr3b != "CASSDAGDTDTQYF"), features = "clonotype_size", slot = "data",  raster=TRUE,  order=TRUE) +
    scale_color_gradientn(trans = "log2", colors = color.code, limits = c(global_min, global_max)) +
    theme(legend.position = "right",
    axis.text = element_blank(),    
        axis.title = element_blank(),   
        axis.ticks = element_blank(),   
        axis.line = element_blank(),   
        panel.background = element_blank(),  
        panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank())  



p <- p1 + p2 + plot_layout(ncol = 1)

ggsave("clusters_size_treatment.pdf", p, width = 2.6, height = 4)



color.code = c("grey80","#F1DF91", "#FBAD46", "#F36E21", "#C62832", "#8A1739", "#4B0E3D")

all_data <- subset(td_TCR, response != "no_data")$clonotype_size
global_min <- min(all_data, na.rm = TRUE)
global_max <- max(all_data, na.rm = TRUE)

p1 <- FeaturePlot(subset(td_TCR, response == "R" & treatment == "pre"), features = "clonotype_size", slot = "data",  raster=TRUE,  order=TRUE) +
    scale_color_gradientn(trans = "log2", colors = color.code, limits = c(global_min, global_max)) +
    theme(legend.position = "right",
    axis.text = element_blank(),    
        axis.title = element_blank(),   
        axis.ticks = element_blank(),   
        axis.line = element_blank(),    
        panel.background = element_blank(),  
        panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank())  

p2 <- FeaturePlot(subset(td_TCR, response == "NR" & treatment == "pre"), features = "clonotype_size", slot = "data",  raster=TRUE,  order=TRUE) +
    scale_color_gradientn(trans = "log2", colors = color.code, limits = c(global_min, global_max)) +
    theme(legend.position = "right",
    axis.text = element_blank(),    
        axis.title = element_blank(),   
        axis.ticks = element_blank(),  
        axis.line = element_blank(),    
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank())  


p3 <- FeaturePlot(subset(td_TCR, response == "R" & treatment == "post"), features = "clonotype_size", slot = "data",  raster=TRUE,  order=TRUE) +
    scale_color_gradientn(trans = "log2", colors = color.code, limits = c(global_min, global_max)) +
    theme(legend.position = "right",
    axis.text = element_blank(),    
        axis.title = element_blank(),   
        axis.ticks = element_blank(),   
        axis.line = element_blank(),   
        panel.background = element_blank(),  
        panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank())  

p4 <- FeaturePlot(subset(td_TCR, response == "NR" & treatment == "post"), features = "clonotype_size", slot = "data",  raster=TRUE,  order=TRUE) +
    scale_color_gradientn(trans = "log2", colors = color.code, limits = c(global_min, global_max)) +
    theme(legend.position = "right",
    axis.text = element_blank(),    
        axis.title = element_blank(),   
        axis.ticks = element_blank(),   
        axis.line = element_blank(),   
        panel.background = element_blank(),  
        panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank())  

feature.lst <- list(p1, p2, p3 ,p4)

p <- wrap_plots(feature.lst, ncol = 2)

ggsave("clusters_size_response.pdf", p, width = 5, height = 4.2)

```




```{r}

td_TCR <- qread("/home/xumeng/TCR_Dynamic/ICB_T/TCR_analysis_2-1/td_TCR.qs", nthreads = 10)

head(td_TCR)

clonosize_clusters_treatment <- td_TCR@meta.data[, c( "cdr3b", "pt", "clonotype_size", "clusters", "treatment")]

rownames(clonosize_clusters_treatment) <- NULL

dim(clonosize_clusters_treatment)

clonosize_clusters_treatment <- subset(clonosize_clusters_treatment, cdr3b != "CASSDAGDTDTQYF")

head(clonosize_clusters_treatment)

dim(clonosize_clusters_treatment)

table(td$TCR)

detailed_stats <- clonosize_clusters_treatment %>%
  group_by(pt, clusters, treatment) %>%
  summarise(
    mean_size = mean(clonotype_size, na.rm = TRUE),
    median_size = median(clonotype_size, na.rm = TRUE),
    # sd_size = sd(clonotype_size, na.rm = TRUE),
    # min_size = min(clonotype_size, na.rm = TRUE),
    # max_size = max(clonotype_size, na.rm = TRUE),
    n = n(),
    .groups = 'drop'
  )

head(detailed_stats)

summary_dat <- detailed_stats %>%  
group_by(clusters, treatment) %>%  
summarise(Mean = mean(mean_size),    
SE = sd(mean_size)/sqrt(n())  )

summary_dat <- detailed_stats %>%  
group_by(clusters, treatment) %>%  
summarise(Median = mean(median_size),    
SE = sd(median_size)/sqrt(n())  )

summary_dat


p <- ggplot() +  
geom_bar(data = summary_dat,
    aes(
      x = treatment, 
      y = as.numeric(Mean), 
      fill = treatment  
    ), 
    stat = "identity", 
    color = "black",   
    linewidth = 0.2, 
    width = 0.7
  ) + 
  geom_point(data = summary_dat, aes(x = treatment, y = as.numeric(Mean)), alpha = 0.7, size = 1.2, stroke = NA, shape = 19)+      
  scale_fill_manual(values = c("#8f8070", "#a54633")) +  
geom_errorbar(data = summary_dat, aes(x = treatment, ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.2, color = "black") +
scale_color_manual(values = c("#8f8070", "#a54633")) +  
facet_grid( ~ clusters, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "Mean Clonosize",
    color = "time status"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  # 坐标轴线宽
    axis.ticks = element_line(linewidth = 0.2), # 刻度线宽
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "top",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) 
p

ggsave("TCR_mean_clonosize_cluster_new.pdf", p, width = 4, height = 2.5)
```



```{r}

clonosize_clusters_treatment <- td_TCR@meta.data[, c( "cdr3b", "pt", "clonotype_size", "clusters", "treatment", "response")]

rownames(clonosize_clusters_treatment) <- NULL

dim(clonosize_clusters_treatment)


head(clonosize_clusters_treatment)

dim(clonosize_clusters_treatment)

table(td$TCR)

detailed_stats <- clonosize_clusters_treatment %>%
  group_by(pt, clusters, treatment, response) %>%
  summarise(
    mean_size = mean(clonotype_size, na.rm = TRUE),
    median_size = median(clonotype_size, na.rm = TRUE),
    n = n(),
    .groups = 'drop'
  )


detailed_stats <- subset(detailed_stats, response != "no_data")

head(detailed_stats)

summary_dat <- detailed_stats %>%  
group_by(clusters, treatment, response) %>%  
summarise(Mean = mean(mean_size),    
SE = sd(mean_size)/sqrt(n())  )


# summary_dat <- detailed_stats %>%  
# group_by(clusters, treatment, response) %>%  
# summarise(Median = mean(median_size),    
# SE = sd(median_size)/sqrt(n())  )

summary_dat

summary_dat <- subset(summary_dat, response != "no_data")

summary_dat$response <- factor(summary_dat$response, levels = c("R", "NR"))

p <- ggplot() +  
geom_bar(data = summary_dat,
    aes(
      x = treatment, 
      y = as.numeric(Mean), 
      fill = treatment 
    ), 
    stat = "identity",  
    position = "stack",
    color = "black",  
    linewidth = 0.05, 
    width = 0.9
  ) +  
scale_fill_manual(values = c("#8f8070", "#a54633")) +  
geom_errorbar(data = summary_dat, aes(x = treatment, ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.2, color = "black") +
scale_y_continuous(expand = c(0, 0), limits = c(0, 50)) +  
scale_color_manual(values = c("#8f8070", "#a54633")) +  
facet_grid(response ~ clusters, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "Mean Clonosize",
    color = "time status"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2),
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "top",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  )  +
  geom_signif(data = subset(detailed_stats, response != "no_data"), aes(x = treatment, y = as.numeric(mean_size)),
    comparisons = list(c("pre", "post")), step_increase = 0.08,
    map_signif_level = F, test = "wilcox.test", test.args=list(alternative = "two.side", paired = FALSE),
    tip_length = c(0), color = "black", size = 0.2, textsize = 2
  )

p


ggsave("TCR_mean_clonosize_cluster_response.pdf", p, width = 4, height = 4)


summary_dat <- detailed_stats %>%  
  group_by(clusters, response, treatment) %>%  
  summarise(
    n = n(),  
    Mean = mean(median_size, na.rm = TRUE),  # 忽略NA
    SE = ifelse(n > 1, sd(median_size, na.rm = TRUE)/sqrt(n), NA)  
  )

head(summary_dat)


clonosize_clusters_treatment <- td_TCR@meta.data[, c( "cdr3b", "clonotype_size", "clusters", "treatment", "TCR_size")]

rownames(clonosize_clusters_treatment) <- NULL

clonosize_clusters_treatment <- subset(clonosize_clusters_treatment, cdr3b != "CASSDAGDTDTQYF")


dim(clonosize_clusters_treatment)


head(clonosize_clusters_treatment)

dim(clonosize_clusters_treatment)

head(clonosize_clusters_treatment)

detailed_stats <- clonosize_clusters_treatment %>%
  group_by(clusters, treatment) %>%
  summarise(
    mean_size = mean(clonotype_size, na.rm = TRUE),
    median_size = median(clonotype_size, na.rm = TRUE),
    n = n(),
    .groups = 'drop'
  )

head(detailed_stats)

library(scales)

colors_use <- c('#fc8d59','#9e9ac8','#96daf7','#fed976','#b0479a','#35978f','#193a1c','#e31a1c','#f9d3d7','#08306b')

p <- ggplot(detailed_stats, aes(x = treatment, y = mean_size, fill = clusters)) +
  geom_bar(stat = "identity", alpha = 0.8, position = "fill") +
  ylab("mean clonosize") +
  xlab("cell_types") +
  ggtitle("") +
  scale_fill_manual(values = colors_use) +
  theme_classic() +
  theme(
    text = element_text(size = 8),
    axis.text.y = element_text(size=8, color = "black"),
    axis.title.y = element_text(size=9, color = "black"),
    axis.text.x = element_text(size=8, color = "black"),
    axis.line = element_line(linewidth = 0.2), 
    axis.ticks = element_line(linewidth = 0.2),
    axis.title.x = element_blank(),
    axis.title = element_text(size = 9),
    axis.text = element_text(size = 8),
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 9, colour = "black") ,
    legend.title = element_text(size = 8),
    legend.text = element_text(size = 7),
    plot.title = element_text(size = 9, hjust = 0.5)
  )


p

ggsave("mean_size_cluster.pdf", p, width = 2, height = 4)



```
















