
```{r}
rm(list = ls())

library(vegan)
library(dplyr)
library(tidyr)
library(purrr)
library(stringr)
library(reshape2)
library(ggplot2)
library(ggsignif)
library(patchwork)
library(qs)


'%ni%'=Negate('%in%')

setwd("/home/xumeng/TCR_Dynamic/code4fithub/Fig3/")

mycol <- c("#D62728", "#1F77B4",  "#FF7F0E", "#2CA02C", "#9467BD", "#8C564B", "#E377C2", "#BCBD22", "#17BECF", "#FF9896", "#AEC7E8", "#FFBB78", "#98DF8A",  "#C5B0D5",  "#C49C94",  "#F7B6D2", "#7F7F7F", "#DBDB8D", "#9EDAE5", "#45aab4","#fe7966","#81d0bb","#f9637c","#fbb45c","#038dT2","#FFDE99","#B8C8F5","#8fa2dc","#feaac2","#206491", "gold", "seagreen", "tomato", "#285d7c", "#f1d19e", "#e5807c", "#d7969a", "#eeebd8", "#d97d56", "#eecca9", "#eeeddb", "#494651", "#4b98a9", "#719eb6", "#679bc5", "#d94248", "#ebd66d", "#62985a", "#ecc832", "#e1a34e", "#ac3241", "#f5812d", "#d63833", "#ef5a30")

```



```{r}

HCD_pbmc <- qread("/home/xumeng/TCR_Dynamic/randomicity/Health_new/PBMC_analysis/health_pbmc_bulk_all.qs")

HCL_pbmc <- qread("/home/xumeng/TCR_Dynamic/randomicity/healthy_donor_files/pbmc_bulk_all.qs")


SARS2_pbmc_2 <- qread("/home/xumeng/TCR_Dynamic/randomicity/SARS2_ID_2024/select/Across6/SARS2_2024_across6_bulk_all.qs")

```


```{r}

calculate_eg_ratio <- function(patient_data, patient_id) {
  map_dfr(7:1, function(i) {
    times <- paste0("T", i:8)
    
    shared_filtered <- patient_data %>%
      filter(time %in% times) %>%
      group_by(cdr3_aa_bl) %>%
      filter(n_distinct(time) > 1) %>%
      ungroup()
    
    t8_eg <- patient_data %>%
      filter(time == "T8", !(cdr3_aa_bl %in% shared_filtered$cdr3_aa_bl))
    
    t8_total <- patient_data %>%
      filter(time == "T8")
    
    eg_ratio <- nrow(t8_eg) / nrow(t8_total)
    
    data.frame(
      patient = patient_id,
      time = 8 - i,
      eg_ratio = eg_ratio
    )
  })
}


patients <- c("P01", "P02", "P03")

head(HCD_pbmc)

HCD_eg_all <- map_dfr(patients, ~{
  patient_data <- HCD_pbmc %>% filter(patient == .x)
  calculate_eg_ratio(patient_data, .x)
})

HCD_eg_all$patient <- paste0(HCD_eg_all$patient, "@HCD")

head(HCD_eg_all)


calculate_eg_ratio <- function(patient_data, patient_id) {
  map_dfr(2:1, function(i) {
    times <- paste0("T", i:3)
    
    shared_filtered <- patient_data %>%
      filter(time %in% times) %>%
      group_by(cdr3_aa_bl) %>%
      filter(n_distinct(time) > 1) %>%
      ungroup()
    
    t3_eg <- patient_data %>%
      filter(time == "T3", !(cdr3_aa_bl %in% shared_filtered$cdr3_aa_bl))
    
    t3_total <- patient_data %>%
      filter(time == "T3")
    
    eg_ratio <- nrow(t3_eg) / nrow(t3_total)
    
    data.frame(
      patient = patient_id,
      time = 3 - i,
      eg_ratio = eg_ratio
    )
  })
}

HCL_pbmc <- HCL_pbmc %>%
  mutate(
    time = case_when(
      time == "W0" ~ "T1",
      time == "W2" ~ "T2",
      time == "W4" ~ "T3",
    )
  )

HCL_pbmc$patient <- paste0(HCL_pbmc$patient, "@HCL")

HCL_pbmc <- subset(HCL_pbmc, patient != "P4@HCL")


patients <- unique(HCL_pbmc$patient)

head(HCL_pbmc)

HCL_eg_all <- map_dfr(patients, ~{
  patient_data <- HCL_pbmc %>% filter(patient == .x)
  calculate_eg_ratio(patient_data, .x)
})


head(HCL_eg_all)





calculate_eg_ratio <- function(patient_data, patient_id) {
  map_dfr(5:2, function(i) {
    times <- paste0("T", i:6)
    
    shared_filtered <- patient_data %>%
      filter(time %in% times) %>%
      group_by(cdr3_aa_bl) %>%
      filter(n_distinct(time) > 1) %>%
      ungroup()
    
    t6_eg <- patient_data %>%
      filter(time == "T6", !(cdr3_aa_bl %in% shared_filtered$cdr3_aa_bl))
    
    t6_total <- patient_data %>%
      filter(time == "T6")
    
    eg_ratio <- nrow(t6_eg) / nrow(t6_total)
    
    data.frame(
      patient = patient_id,
      time = 6 - i,
      eg_ratio = eg_ratio
    )
  })
}


SARS2_pbmc_2 <- subset(SARS2_pbmc_2, time != "T1")


patients <- unique(SARS2_pbmc_2$patient)

head(SARS2_pbmc_2)

SARS2_eg_all <- map_dfr(patients, ~{
  patient_data <- SARS2_pbmc_2 %>% filter(patient == .x)
  calculate_eg_ratio(patient_data, .x)
})

SARS2_eg_all$patient <- paste0(SARS2_eg_all$patient, "@SARS2")

head(SARS2_eg_all)

```





```{r}

eg_all <- bind_rows(HCD_eg_all, HCL_eg_all, SARS2_eg_all)

head(eg_all)


eg_all <- eg_all %>%
  mutate(datasets = str_split(patient, "@", simplify = TRUE)[, 2])

library(ggsci)

colors <- ggsci::pal_jama()(7)

p <- ggplot(eg_all, aes(x = time, y = eg_ratio, group = patient, color = datasets)) +
  geom_line(aes(color = datasets), linewidth = 0.2) +
  geom_point(aes(color = datasets), size = 1.2) + 
   scale_x_continuous(breaks = 1:7) +   
  labs(
    title = "",
    x = "Number of Pre Timepoints",
    y = "Time-specific TCR Ratio"
  ) +
  theme_classic() +
#   scale_color_jama()+
  scale_color_manual(values = colors[c(4,6,3)]) + 
  theme(
    axis.text.x = element_text(size=6, color = "black"),
    axis.text.y = element_text(size=6, color = "black"),
    # axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "top",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) 

p


```