
```{r}

rm(list = ls())

library(ggpmisc)
library(tidyr)
library(dplyr)
library(stringr)
library(reshape2)
library(ggsignif)
library(patchwork)
library(qs)
library(aplot)
library(ggsci)

'%ni%'=Negate('%in%')

setwd("/home/xumeng/TCR_Dynamic/code4fithub/Fig3/")


```

## Extended Data Fig. 2c


```{r}

bulk <- qread("/home/xumeng/TCR_Dynamic/randomicity/Health_new/PBMC_analysis/health_pbmc_bulk_all.qs")

```


```{r}

head(bulk)

data4dis <- bulk[, c("cdr3_aa_bl", "count_bl", "patient", "time")] %>% unique()


data4dis_wide <- data4dis %>%
  pivot_wider(
    names_from = time,       
    values_from = count_bl,  
    values_fill = list(count_bl = 0)  
  )

data4dis_wide <- data4dis_wide %>%
  mutate(
    non_zero_count = rowSums(across(starts_with("T")) > 0),
    status = case_when(
      non_zero_count == 1 ~ "only",
      non_zero_count == 2 ~ "across2",
      non_zero_count == 3 ~ "across3",
      non_zero_count == 4 ~ "across4",     
      non_zero_count == 5 ~ "across5",     
      non_zero_count == 6 ~ "across6",     
      non_zero_count == 7 ~ "across7",     
      non_zero_count == 8 ~ "across_all",
      TRUE ~ "other"
    )
  )


```


```{r}

data4dis_long <- data4dis_wide %>%
  gather(key = "time", value = "count", T1, T2, T3, T4, T5, T6, T7, T8)

data4dis_long_1 <- subset(data4dis_long, count > 0)


data4dis_long_1$time_status <- paste0(data4dis_long_1$time, "@", data4dis_long_1$status)

data4dis_long_1$sampleid <- paste0(data4dis_long_1$patient, "@", data4dis_long_1$time)

pat_status <- table(data4dis_long_1$patient, data4dis_long_1$time_status) %>% as.data.frame()


group = "time_status"

colnames(pat_status) <- c("patient", group, "count")

pat_status <- pat_status %>%
  mutate(time = str_split(time_status, "@", simplify = TRUE)[, 1])

pat_status <- pat_status %>%
  mutate(status = str_split(time_status, "@", simplify = TRUE)[, 2])

pat_status$sampleid <- paste0(pat_status$patient, "@", pat_status$time)



pat_status <- pat_status %>%
  group_by(sampleid) %>%
  mutate(proportion = count / sum(count))

colnames(pat_status)[2] <- "group"


pat_status$status <- factor(pat_status$status, levels = c("only", "across2", "across3", "across4", "across5", "across6", "across7", "across_all"))


p2 <- ggplot(pat_status, aes(x = status, y = as.numeric(proportion), color = status)) +
  geom_boxplot(alpha = 0.3, outliers = F, linewidth = 0.2) + 
  # scale_fill_manual(values = mycol) + 
# geom_line(aes(group = patient), color = "grey", alpha = 0.8, lwd = 0.4, position = position_dodge(0.5))+ 
geom_jitter(aes(color = status), size=0.8)+
# scale_color_manual(values = color_all) +  
scale_color_npg() +  
facet_wrap(~ time, ncol = 4, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "TCR Type Ratio",
    # fill = "Metric",
    color = "time status"
  ) +
  theme_classic() +
  theme(
   axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "none",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) 

p2


data4dis_long_1 <- data4dis_long_1 %>%
  group_by(sampleid) %>%
  mutate(expansion = ifelse(count >= 1.5*median(count), "ex", "nex")) %>%
  ungroup()

data4dis_long_1$patient_time_status <- paste0(data4dis_long_1$patient, "@", data4dis_long_1$time, "@", data4dis_long_1$status)

ex_data <- data4dis_long_1 %>%
  group_by(patient_time_status, expansion) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(patient_time_status) %>%
  mutate(proportion = count / sum(count)) %>%
  ungroup()

ex_data <- ex_data %>%
  mutate(patient = str_split(patient_time_status, "@", simplify = TRUE)[, 1])

ex_data <- ex_data %>%
  mutate(time = str_split(patient_time_status, "@", simplify = TRUE)[, 2])

ex_data <- ex_data %>%
  mutate(status = str_split(patient_time_status, "@", simplify = TRUE)[,3])

ex_data$time_status <- paste0(ex_data$time, "@", ex_data$status)

status_levels <- c("only", "across2", "across3", "across4", "across5", "across6", "across7","across_all")

ex_data$status <- factor(ex_data$status, levels = status_levels)

p3 <- ggplot(subset(ex_data, expansion == "ex"), aes(x = status, y = as.numeric(proportion), color = status)) +
  geom_boxplot(alpha = 0.3, outliers = F, linewidth = 0.2) + 
geom_jitter(aes(color = status), size=0.8)+
# scale_color_manual(values = color_all) +  
scale_color_npg() +  
facet_wrap(~ time, ncol = 4, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "Expanded TCR Ratio",
    # fill = "Metric",
    color = "time status"
  ) +
  theme_classic() +
  theme(
   axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "bottom",
    legend.text = element_text(size=5),
    legend.title = element_text(size=6),
    legend.key.size = unit(10, "pt")
  ) +
  guides(color = guide_legend(byrow = TRUE, ncol = 10))

p3


```



## Extended Data Fig. 2c


```{r}

bulk <- qread("/home/xumeng/TCR_Dynamic/randomicity/SARS2_ID_2024/select/Across6/SARS2_2024_across6_bulk_all.qs")

```

```{r}

head(bulk)

data4dis <- bulk[, c("cdr3_aa_bl", "count_bl", "patient", "time")] %>% unique()

data4dis <- subset(data4dis, time != "T1")


data4dis_wide <- data4dis %>%
  pivot_wider(
    names_from = time,       
    values_from = count_bl,  
    values_fill = list(count_bl = 0)  
  )

data4dis_wide <- data4dis_wide %>%
  mutate(
    non_zero_count = rowSums(across(starts_with("T")) > 0),
    status = case_when(
      non_zero_count == 1 ~ "only",
      non_zero_count == 2 ~ "across2",
      non_zero_count == 3 ~ "across3",
      non_zero_count == 4 ~ "across4",     
      non_zero_count == 5 ~ "across_all",
      TRUE ~ "other"
    )
  )

```


```{r}

data4dis_long <- data4dis_wide %>%
  gather(key = "time", value = "count", T2, T3, T4, T5, T6)


data4dis_long_1 <- subset(data4dis_long, count > 0)


data4dis_long_1$time_status <- paste0(data4dis_long_1$time, "@", data4dis_long_1$status)

data4dis_long_1$sampleid <- paste0(data4dis_long_1$patient, "@", data4dis_long_1$time)


pat_status <- table(data4dis_long_1$patient, data4dis_long_1$time_status) %>% as.data.frame()


group = "time_status"

colnames(pat_status) <- c("patient", group, "count")


pat_status <- pat_status %>%
  mutate(time = str_split(time_status, "@", simplify = TRUE)[, 1])

pat_status <- pat_status %>%
  mutate(status = str_split(time_status, "@", simplify = TRUE)[, 2])

pat_status$sampleid <- paste0(pat_status$patient, "@", pat_status$time)

pat_status <- pat_status %>%
  group_by(sampleid) %>%
  mutate(proportion = count / sum(count))

colnames(pat_status)[2] <- "group"

pat_status$status <- factor(pat_status$status, levels = c("only", "across2", "across3", "across4", "across_all"))

p2 <- ggplot(pat_status, aes(x = status, y = as.numeric(proportion), color = status)) +
  geom_boxplot(alpha = 0.3, outliers = F, linewidth = 0.2) + 
  # scale_fill_manual(values = mycol) + 
# geom_line(aes(group = patient), color = "grey", alpha = 0.8, lwd = 0.4, position = position_dodge(0.5))+ 
geom_jitter(aes(color = status), size=0.8)+
# scale_color_manual(values = color_all) +  
scale_color_jama() +  
facet_wrap(~ time, ncol = 6, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "TCR Type Ratio",
    # fill = "Metric",
    color = "time status"
  ) +
  theme_classic() +
  theme(
   axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "none",
    legend.text = element_text(size=6),
    legend.title = element_text(size=7),
  ) 

p2


data4dis_long_1 <- data4dis_long_1 %>%
  group_by(sampleid) %>%
  mutate(expansion = ifelse(count >= 1.5*median(count), "ex", "nex")) %>%
  ungroup()

data4dis_long_1$patient_time_status <- paste0(data4dis_long_1$patient, "@", data4dis_long_1$time, "@", data4dis_long_1$status)

ex_data <- data4dis_long_1 %>%
  group_by(patient_time_status, expansion) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(patient_time_status) %>%
  mutate(proportion = count / sum(count)) %>%
  ungroup()

ex_data <- ex_data %>%
  mutate(patient = str_split(patient_time_status, "@", simplify = TRUE)[, 1])

ex_data <- ex_data %>%
  mutate(time = str_split(patient_time_status, "@", simplify = TRUE)[, 2])

ex_data <- ex_data %>%
  mutate(status = str_split(patient_time_status, "@", simplify = TRUE)[,3])

ex_data$time_status <- paste0(ex_data$time, "@", ex_data$status)

status_levels <- c("only", "across2", "across3", "across4", "across_all")

ex_data$status <- factor(ex_data$status, levels = status_levels)

p3 <- ggplot(subset(ex_data, expansion == "ex"), aes(x = status, y = as.numeric(proportion), color = status)) +
  geom_boxplot(alpha = 0.3, outliers = F, linewidth = 0.2) + 
geom_jitter(aes(color = status), size=0.8)+
# scale_color_manual(values = color_all) +  
scale_color_jama() +  
facet_wrap(~ time, ncol = 6, scales = "fixed") +
  labs(
    title = "",
    x = "",
    y = "Expanded TCR Ratio",
    # fill = "Metric",
    color = "time status"
  ) +
  theme_classic() +
  theme(
   axis.text.x = element_blank(),
    axis.text.y = element_text(size=6, color = "black"),
    axis.ticks.x = element_blank(),
    axis.title.y=element_text(size=7, color = "black"),
    axis.title.x=element_blank(),
    axis.line = element_line(linewidth = 0.2),  
    axis.ticks = element_line(linewidth = 0.2), 
    panel.grid=element_blank(),
    strip.background = element_rect(color = "white", fill = "white"),
    strip.text.x = element_text(size = 7, colour = "black"),
    legend.position = "none",
    legend.text = element_text(size=5),
    legend.title = element_text(size=6),
    legend.key.size = unit(10, "pt")
  ) +
  guides(color = guide_legend(byrow = TRUE, ncol = 10))

p3


```



